go.sum, pkg/gds/certs.go, pkg/gds/secret.go, pkg/gds/secret_test.go, pkg/gds/server.go
In #14 we introduced the new secret package, which allowed us to refactor the password storage and retrieval process to Google Secret Manager for consistency across projects. 
In this PR, I have similarly updated the certificate storage to store zipped certificates directly to Secret Manager as bytes. The only catch is that as currently implemented, the TRISA trust package requires that zipped certificates be [read in as files from disk](https://github.com/trisacrypto/trisa/issues/51); so the tests added to validate that cert storage is working as expected leverage an intermediate temporary file write/delete.  
In the process of working on this PR, I also experimented more with the Google Secret Manager API to see what other kinds of errors can arise; the main one that I think we want to …
=> Write certificates to Secret Manager

go.mod, go.sum, pkg/gds/certs.go, pkg/gds/emails/client.go, pkg/gds/emails/client_test.go, pkg/gds/emails/emails_test.go, pkg/gds/emails/templates/review_request.html, pkg/gds/emails/templates/review_request.txt
Performs better handling of sending emails to technical, admin, billing,
and legal contacts. First, a check is added to ensure the contact is not
nil and that it has an email address, otherwise it is skipped. Sending
does not stop on the first error, but all email addresses are tried to
make sure at least one email can get out. The number of errors are
reported via logging rather than returned. If no messages were delivered
then the function returns an error.
This PR also updates the Registration Review email to be nicely rendered
YAML with string enums and no empty fields.
Fixes #31
Fixes #32
=> Better contact handling in email client senders

pkg/gds/config/config.go, pkg/gds/logger/logger.go, pkg/gds/server.go
By default GDS now emits JSON formatted logs for parsing in a cloud
console. This PR also adds GCP severity levels for GCP-specific parsing
of logs. The logger is added to its own module so other cloud-specific
handlers can be added as needed.
Fixes #33
=> Implements JSON logging with GCP severity

cmd/gds/main.go, cmd/gdsutil/main.go, pkg/gds/config/config.go, pkg/gds/config/config_test.go, pkg/gds/server.go, pkg/gds/store/leveldb/index.go, pkg/gds/store/leveldb/leveldb.go, pkg/gds/store/store.go
This PR more intelligently handles leveldb indices and reindexing by allowing a configuration that forces reindex on boot and creates a maintenance mode that allows database interactions from the command line. 
Updates the database configuration to accept a bool for reindexing on
boot and the store reindexes if necessary on open. Adds a call to sync
to on Backup so that the indices are resync'd routinely.
Fixes #30
This commit enables more compact LevelDB indices by compressing them
before writing them to disk. However, this requires deleting old indices
and regenerating them. To facilitate this, during maintenance mode, the
database no longer opens a connection to the database or runs any
management processes. This will allow us to ssh into the server and
access the database as needed to …
=> Reindex and gzip index sync without DB in maintenance mode

pkg/gds/store/mockdb/mockdb.go
Usage: 
Anywhere that you need to test but don't want to actually call a database you can use the mock struct instead of Level. When you write the test you create the `On` version of the function and that's what will run during the test. You can also check if the `Invoked` bool is true to ensure it ran (vs not throwing an error because it didn't run). Will be used in #66
=> Add mock db

cmd/gdsutil/main.go, pkg/gds/replica.go, pkg/gds/store/store.go, pkg/gds/store/wire/testdata/certreqs::87657b4d-e72c-4526-9332-c8fc56adb367.json, pkg/gds/store/wire/testdata/index::categories.json, pkg/gds/store/wire/testdata/index::names.json, pkg/gds/store/wire/testdata/peers::8.json, pkg/gds/store/wire/testdata/vasps::838b1f57-1646-488d-a231-d71d88681cfa.json, pkg/gds/store/wire/wire.go, pkg/gds/store/wire/wire_test.go
This PR creates a helper pkg, wire for marshaling and unmarshaling
object data from disk and memory - standardizing how we handle objects
for replication. It also adds NamespaceReplicas to ensure that Peers are
also replicated. This PR should delete and simplify a lot of code.
=> Better object management

cmd/sectigo/main.go, pkg/sectigo/README.md, pkg/sectigo/endpoints.go, pkg/sectigo/sectigo.go, pkg/sectigo/serializers.go
Implements the Sectigo upload CSR method for the client, allowing multi-part uploads of certificate signing requests plus other form data required to create a certificate batch request using this method.
TODO: right now I'm getting 500 Internal Server Error responses from Sectigo … which does not make it easy to debug things. I've tried a bunch of different things to try to get around the error; but I'm going to have to put in a call to Sectigo support to figure out what is going on.
=> Implements Sectigo CSR Client Method

cmd/gdsutil/main.go, pkg/gds/config/config.go, pkg/gds/config/config_test.go, pkg/gds/global/v1/interface.go, pkg/gds/global/v1/namespaces.go, pkg/gds/jitter/jitter.go, pkg/gds/jitter/jitter_test.go, pkg/gds/replica.go, pkg/gds/store/leveldb/leveldb.go, pkg/gds/store/leveldb/objects.go, pkg/gds/store/leveldb/objects_test.go, pkg/gds/store/store.go, pkg/gds/store/wire/wire.go, pkg/gds/store/wire/wire_test.go
This PR finalizes the v1.1 Gossip implementation though it is not ready
for production release quite yet. Our intent is to run GDS with the
replica server disabled but to have object versioning in place. The
cleanup PR creates the ObjectStore abstraction to remove directly use of
leveldb and implements the routine that initiates Gossip with remote
replicas.
=> Gossip cleanup

web/src/components/LookupResults.js, web/src/lib/country.js
If the country field of the VASP record was missing, the UI crashed and
displayed a blank page. This PR fixes this by checking for the presence
of the country field and not displaying it rather than trying to produce
the flag emoji.
=> Fix front-end crash on empty country

cmd/gdsutil/main.go, web/src/components/Contact.js, web/src/components/Registration.js
Per the attribution team: the admin contact and phone number is required
for verification. This PR enables Front-End validation of these fields,
though the backend does not enforce it.
=> Make Admin contact and phone number required

cmd/gds/main.go, cmd/gdsutil/main.go
This PR is the first step towards automatic transferal of TestNet registrations to Production registrations; it allows us to directly access the database and export a registration form that can be uploaded manually to the production UI.
The UI fix is to remarshal the registration form JSON to ensure that all fields are included even if they have the `omitempty` tag from the Go files generated from the protocol buffers.
=> Registration Export Tool

cmd/gds/main.go, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client_test.go
Adds a query param to the vasp list endpoint to filter by verification
status. The verification status must match one of the protocol buffer
verification status strings, but is case and whitespace insensitive.
Fixes SC-577
=> GDS Admin API: Filter VASP list by status

cmd/gds/main.go, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go
This endpoint provides a mechanism to retrieve the details for a VASP
that are required for the Admin UI - including some computed values and
extra information that are not standard in the pb.VASP record.
Fixes SC-571
TODO:
=> GDS Admin API: VASP Detail Endpoint

cmd/gds/main.go, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go
Implements a summary endpoint to create a dashboard for TRISA admins
that lets them know the current state of the GDS including aggregate
counts of contacts, registrations, and certificate requests.
Fixes SC-576
=> GDS Admin API: Summary Endpoint

cmd/gds/main.go, containers/docker-compose.yaml, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go, pkg/gds/store/leveldb/iterator.go
Implements an endpoint that returns a mapping of all VASP names (legal
entity names, common name, website) to its UUID for use in the search
bar of the Admin UI. The result is a simple mapping, but more
requirements are required from the front end to know what data is
required in the return statement.
Fixes SC-583
Blocked by #103
=> GDS Admin API: Autocomplete Endpoint

pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client_test.go, pkg/gds/models/v1/models.go
The VASP List endpoint required both verified and unverified contacts to
display badges correctly in the UI. This PR adapts the response to
return a map of contact name to verified bool rather than just a list of
verified contacts.
Unblocks SC-594
=> Better Verified Contacts Handling

pkg/gds/admin.go
An error occurred when the contact was nil and the Extra data was being
sanitized. This PR "fixes" it by performing a nil check on the contact
first. However, it is likely we should simply have "sanitize"
functionality for contacts in the future.
=> Bugfix: Contact Sanitization nil Error

pkg/gds/admin.go, pkg/gds/admin/v2/csurf.go, pkg/gds/admin/v2/csurf_test.go, pkg/gds/admin/v2/errors.go, pkg/gds/secrets/token.go
Implements the double cookie middleware for CSRF protection in the Admin
API. The CSRF protection relies on a cookie that is HttpOnly, e.g. one
that cannot be read in JavaScript and one that can be. The client
responsibility is to read the cookie that can be read and submit it in
an X-CSRF-TOKEN header with the request.
TODO:
=> Implements Double Cookie Middleware

containers/.env.template, containers/docker-compose.yaml, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/auth.go, pkg/gds/admin/v2/auth_test.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go, pkg/gds/admin/v2/csurf.go, pkg/gds/config/config.go, pkg/gds/config/config_test.go, pkg/gds/tokens/tokens.go, pkg/gds/tokens/tokens_test.go, web/gds-admin-ui/src/pages/account/Login.js
Implements Authentication and Reauthentication endpoints.
Authentication requires a Google Identity Services token, which is verified using the [`idtoken`](https://pkg.go.dev/google.golang.org/api/idtoken#Validate) package. If it is a valid Google token, then access and refresh tokens are issued. 
Reauthentication requires the access token in the header, even if it is expired and the refresh token submitted in the body. Once the access and refresh tokens are compared and verified new tokens are returned. 
Both Authentication and Reauthentication requires double cookie CSRF protection since they are POST endpoints that modify state on the server. Therefore I've also added a `GET /v2/authenticate` method that is handled by `ProtectAuthenticate` - this function sets the cookies on the …
=> Implements Authentication and Reauthentication endpoints

pkg/gds/admin.go, pkg/gds/admin/v2/auth.go, pkg/gds/admin/v2/auth_test.go, pkg/gds/admin/v2/csurf_test.go, pkg/gds/tokens/mock.go
Adds middleware that checks the Bearer JWT token from the Authorization
header before permitting the request to continue.
TODO:
=> Authorization Middleware

pkg/gds/admin.go, pkg/gds/certs.go, pkg/gds/gds.go, pkg/gds/models/v1/models.go, pkg/gds/models/v1/models_test.go
This adds a new function `UpdateVerificationStatus` which updates the verification state of a VASP and appends an entry to the audit log to record the state change. State changes have been refactored to use this new function instead of just assigning a new value to `VASP.VerificationStatus`.
=> VASP update state change refactor

cmd/gds/main.go, cmd/gdsutil/main.go, containers/docker-compose.yaml, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go, pkg/gds/config/config.go, pkg/gds/config/config_test.go, pkg/gds/tokens/tokens.go
To ensure the CLI still works on the MVP release, this PR adds private
key based authentication to the CLI to avoid having to go through the
OAuth2 workflow. This mechanism will be replaced in the future but is a
stop gap for now.
=> Simple CLI Authentication

pkg/gds/tokens/tokens.go, pkg/gds/tokens/tokens_test.go
Fixes a bug where the refresh token duration was the same as the
access token duration. Adds tests to ensure the relative timestamps of
access and refresh tokens are correct.
@elysee15 this unblocks #136 and SC-581
Fixes SC-1175
=> Fix refresh time duration

web/gds-admin-ui/src/layouts/LeftSidebar.js, web/gds-admin-ui/src/pages/account/AccountLayout.js, web/gds-admin-ui/src/pages/app/dashboard/Status.js, web/gds-admin-ui/src/pages/app/dashboard/Tasks.js, web/gds-admin-ui/src/pages/app/dashboard/TasksChart.js, web/gds-admin-ui/src/pages/app/dashboard/index.js, web/gds-admin-ui/src/pages/error/PageNotFound.js, web/gds-admin-ui/src/pages/error/PageNotFoundAlt.js, web/gds-admin-ui/src/pages/error/ServerError.js, web/gds-admin-ui/src/utils/index.js
Fixes SC-1455
This is a fix to update the logo on login and not found screens based on `IS_TESTNET` variable. 
The purpose of this variable is to be able to know which logo should be appear on the screen either `VASP Directory` or `TESTNET`
Another story for that has been created by @bbengfort  `SC-1486` if you want to have his explanation
=> fix: modify logo on login and not-found screen according to environment

pkg/gds/admin.go, pkg/gds/models/v1/models.go
This fixes two issues @elysee15 discovered with the review notes endpoint.
1. The notes endpoint was configured at `v2/:vaspID/notes`, it should be `v2/vasps/:vaspID/notes`.
2. The review notes handlers run into a nil exception when a VASP contains no review notes.
=> fix routing and nil map

web/gds-ui/src/components/select/LanguageSelect.js
Change the “中国人” here into “中文“. What we now have is “Chinese people” but better change it into the “Chinese language”, which is “中文“
=> Change Chinese language dropdown label

pkg/gds/admin.go
This fixes an uninitialized pointer in `ListReviewNotes` which is the actual bug that @elysee15 is getting the 500 error from when calling the notes endpoint.
=> fix uninitialized pointer

cmd/gds/main.go, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go, pkg/gds/models/v1/models.go, pkg/gds/models/v1/models_test.go
This changes the `CreateReviewNote` endpoint a bit so that it returns the newly created note instead of just the ID slug, which makes the review note handling on the front end a bit easier.
=> sc-1804 return note from CreateNote endpoint

web/gds-ui/src/contexts/LanguageContext.js
This PR adds the `loadLocaleData` function to avoid this error message:
```
index.js:1 Plurals for locale en aren't loaded. Use i18n.loadLocaleData method to load plurals for specific locale. Using other plural rule as a fallback.
```
=> Load locale data for GDS-UI to avoid plural error msg

cmd/gds/main.go, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client.go, pkg/gds/admin/v2/client_test.go, pkg/gds/models/v1/models.go, pkg/gds/models/v1/models_test.go
This makes a change to the `UpdateReviewNote` endpoint so that it returns the updated note rather than an empty success reply, similar to the change that was just made for the `CreateReviewNote` endpoint.
=> sc-1864 return note from update endpoint

.dockerignore, containers/build.sh, containers/trtl/Dockerfile
This PR adds the TRTL Dockerfile and updates the GDS Dockerfile to be a
bit lighter-weight and share cache with the TRTL Dockerfile in order to
reduce build times. The GDS container has decreased from 175MB to 132MB
as a result of these changes.
=> GDS Containers Update

cmd/gds/main.go, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin/v2/client_test.go
This allows multiple status filters to be passed into the `ListVASPs` endpoint in the GET params. The GET requests end up looking like this:
`/v2/vasps?status_filters=pending_review&status_filters=verified`
I also included the pagination bug fix here, since I was in the area anyway.
=> sc-2059 allow multiple status filters

cmd/trtl/main.go, go.mod, pkg/trtl/honu.go, pkg/trtl/honu_test.go
This PR implements trtl's Delete method, with some preliminary tests and an (untested) prototype CLI command. 
I've opened several follow on issues to deal with the honu issue we uncovered whilst working on this PR (doesn't currently handle namespaces) and the test fixtures (bypassing honu loading results in unexpected metadata).
=> Implements trtl delete

pkg/gds/admin.go, pkg/gds/admin_test.go, pkg/gds/mock.go
This adds a table test to make sure that the admin API routes do not accept unauthenticated requests.
=> sc-2167 authentication middleware test

pkg/gds/gds_test.go, pkg/gds/mock.go, pkg/gds/secrets/mock.go, pkg/gds/service_test.go
This adds a test for the GDS Register RPC. The test itself is pretty straightforward, but I did have to add the mocked secret manager to the mocked service to get the password code to work, and change up how we're starting/stopping the bufconn listener due to a bug I encountered.
=> sc-2187 GDS register test

pkg/gds/admin.go, pkg/gds/admin_test.go, pkg/gds/mock.go, pkg/gds/tokens/mock.go, pkg/gds/tokens/tokens.go
This adds the missing test cases for successful authentication on the Admin API `Authenticate` endpoint. The Admin API handler uses Google's `idtoken.Validate()` and is expecting a Google token. I got around this by adding a `validate` function to the token manager which must be configured when a new `TokenManager` is instantiated. When we're running the tests, the mocked `TokenManager` will be used which uses a mocked validation function instead of the Google one. The mocked function simply parses the token and injects the claims into the returned payload, bypassing all the checks that the Google handler is doing. This allows us to test that we are handling authentication properly assuming that we were passed a valid credential.
=> sc-2163 test case for successful Admin API authentication

cmd/sectigo/main.go, pkg/gds/certs.go, pkg/sectigo/mock/mock.go, pkg/sectigo/sectigo.go, pkg/sectigo/sectigo_test.go, pkg/sectigo/serializers.go
This PR implements the batch status Sectigo API endpoint. If the batch
detail for a certificate request comes back with an unknown status then
the certificate manager attempts to lookup the batch status directly.
Logging for this error is improved.
Fixes SC-2353
=> Hotfix: Handle Sectigo COLLECTED batch detail status

pkg/gds/gds.go, pkg/gds/gds_test.go
This makes some changes to the GDS RPCs to add the contact email as the "source" for the audit logs. Also, new audit log entries are created for verified contacts.
=> sc-2354 add contact email to audit log on GDS RPCs

pkg/trtl/config/config.go, pkg/trtl/interceptor.go, pkg/trtl/trtl.go, pkg/trtl/trtl_test.go
This PR introduces a maintenance mode for trtl that is similar to the maintenance mode we have for GDS; it allows the underlying trtl database to be accessible outside the context of normal operations (e.g. migrations, repairs, etc). 
One observation is that we may want to create another story for introducing a `Status` endpoint for trtl, since that is not currently defined in the protos; this is probably related to the work we'll do in sc-952.
=> Trtl maintenance mode sc-2047

pkg/gds/admin_test.go, pkg/gds/emails/mock.go, pkg/gds/gds_test.go, pkg/gds/service_test.go
This adds an assert helper which hopefully makes it easier to verify which emails are sent in the tests, by checking against both the audit log and the email mock.
=> sc-1343 verify emails sent in tests

pkg/gds/gds.go, pkg/gds/gds_test.go, pkg/gds/store/leveldb/leveldb.go
Modifies the VASP search to allow for prefix searches if the query > 3 characters. For example the query `"alice"` will match "AliceCoin" bu the query `"al"` will not. The search remains case-insensitive. Note that searches such as `"trisa-"` or `"trisa."` now return far more results since the common name field is also included.
=> GDS: Fuzzy Search Fix

web/gds-admin-ui/src/__tests__/certificate-details.js, web/gds-admin-ui/src/assets/scss/app-creative.scss, web/gds-admin-ui/src/pages/app/details/CertificateDetails.js, web/gds-admin-ui/src/pages/app/details/CertificateDetails/Detail.js, web/gds-admin-ui/src/pages/app/details/CertificateDetails/Details.js, web/gds-admin-ui/src/pages/app/details/CertificateDetails/index.js
I preferred to use the accordion because for me it’s easier for the user experience
=> feat: certificate details issuer and subject accordions

pkg/gds/store/load_test.go, pkg/gds/store/mockdb/mockdb.go, pkg/gds/store/testdata/bad_format.csv, pkg/gds/store/testdata/empty.csv, pkg/gds/store/testdata/invalid_country.csv, pkg/gds/store/testdata/invalid_url.csv, pkg/gds/store/testdata/vasps.csv
This adds some tests for `store.Load` which loads VASPs from a CSV file. In order to make the testing easier I changed the `mockdb` struct a bit, although I don't think we were using it before so it shouldn't affect anything.
=> sc-2346 CSV load test

pkg/gds/config/config_test.go, pkg/sectigo/config_test.go
This fills out some test coverage for the remaining config validation functions.
=> sc-2352 config validation tests

pkg/gds/gds.go, pkg/gds/gds_test.go
This adds validation checks of the common name and endpoint to the GDS `Register` endpoint to ensure we aren't sending bad requests to Sectigo.
=> sc-1931 endpoint and common name validation

pkg/gds/certs.go
This PR implements a fix to the Batch Validation Error we were getting when attempting to issue the Hodlbum certificates. We've taken three actions:
1. Added extra logging to better diagnose Sectigo request issues
2. Added `organizationName` to the single batch certificate request params
3. Removed spaces and simplified the `batchName` parameter. 
It isn't clear which of 2 or 3 fixed the bug, but the new request successfully issued certs. 
Merging without review to get this hot-fixed ASAP.
=> Hotfix: Sectigo Batch Validation Error

cmd/trtl/main.go, pkg/gds/client/profile.go, pkg/gds/client/profiles.go
This PR implements client-side mTLS for Trtl
If you have `TRISA_DIRECTORY_REPLICA_URL=localhost:4435` set in your local `.env`, you can remove it.
=> Client-side mTLS for Trtl

README.md, cmd/gds/main.go, cmd/gdsutil/main.go, cmd/trtl/main.go, pkg/gds/client/editor.go
This extension allows you to use --edit with the gds profiles, gdsutil
profiles, and trtl profiles command to directly edit the profiles YAML
in the command line with vim, emacs, or nano. You can specify the editor
of your choice using the $EDITOR environment variable. Note however that
a forking editor like VSCode will not work with this CLI app right now.
=> Edit client profiles from the command line

pkg/gds/admin.go
This changes the duplicate name warning on the autocomplete endpoint to a debug to avoid the alert spam.
=> sc-2540 change duplicate name warning to debug

pkg/gds/config/config_test.go, pkg/sectigo/config.go, pkg/sectigo/sectigo.go
This fixes two things related to the sectigo configuration for the dev environment. The first is that the `SECTIGO_TESTING` flag was not being picked up from the configuration. The second is that GDS was erroring on startup if the sectigo testing flag was set. This has been fixed by moving the localhost check to when we try to send requests instead of on startup. This allows us to boot up GDS in Sectigo testing mode without it crashing.
=> sc-2938 fix sectigo testing behavior for dev

pkg/gds/admin.go
This removes the ignore of the LegalPerson error now that we have patched the validation check in TRISA.
=> sc-2407 Remove ignore of LegalPerson error

pkg/gds/admin.go, pkg/gds/certs.go, pkg/gds/members.go, pkg/gds/store/iterator/iface.go, pkg/gds/store/leveldb/iterator.go
This changes the `DirectoryIterator` methods so that they return an error if we are unable to parse the object from the database. This allows us to better distinguish between iteration errors and parsing errors (corrupted data) when iterating over VASPs or CertReqs.
=> sc-848 DirectoryIterator improved error handling

pkg/gds/store/trtl/trtl.go
This adds the beginnings of the trtl store package with unimplemented stubs for the `DirectoryStore` and `CertificateStore` methods.
=> sc-2466 add trtl store package

go.mod, go.sum, pkg/gds/admin.go, pkg/gds/emails/client.go, pkg/gds/gds.go, pkg/gds/models/v1/contacts.go, pkg/gds/models/v1/contacts_test.go, pkg/gds/models/v1/models.go, pkg/gds/models/v1/models_test.go
This adds some utilities for dealing with the contacts. The main thing is a way to iterate through the contacts on a VASP more easily. Previously, we had to specify the contacts in a slice and then iterate through that slice every time a function wanted to iterate through the contacts. This PR adds two functions for iteration, `IterContacts` and `IterVerifiedContacts`, which both return anonymous functions which can be used to perform the iteration. This ensures that we are always iterating through the contacts in the same order and gets us access to the contact "kinds" if we need them ("technical", "administrative", "legal", and "billing").
=> sc-916 improve contact handling

.github/workflows/tests.yaml, proto/gds/models/v1/models.proto
This adds a code generation step to the GitHub workflow to verify that the protocol buffers build correctly. This has a dependency on the trisacrypto/trisa repo so that repository is checked out to a separate directory before doing the generation.
=> sc-2013 add code generation to workflow

README.md, pkg/gds/client/profiles.go, pkg/trtl/metrics.go, pkg/trtl/metrics/metrics.go, pkg/trtl/replica/replica.go, pkg/trtl/replica/sync.go, pkg/trtl/server.go, pkg/trtl/trtl.go
This PR adds replication monitoring to Trtl with prometheus, moving metrics into a standalone package that can be accessed from the various places within `trtl` where we'd like to be tracking behavior.
Requirements:
=> Anti-entropy metrics with prometheus sc-2365 (v2)

pkg/gds/certs_test.go, pkg/sectigo/mock/mock.go, pkg/sectigo/sectigo_test.go
This adds some tests for the certificate manager to verify that we are building the sectigo request parameters properly. In order to do this, some validation code was added to the sectigo mock which checks if the provided parameters match the required parameters for `ProfileCipherTraceEndEntityCertificate` and `ProfileCipherTraceEE`.
=> sc-3009 sectigo cert profiles tests

containers/docker-compose.yaml, containers/grpc-proxy/Dockerfile, containers/grpc-proxy/envoy.yaml
This is a fix for the `"unknown service /trisa.gds.api.v1beta1.DirectoryService"` error when running the GDS UI with grpc-web in docker compose. The problem was a trailing slash in the `REACT_APP_GDS_API_ENDPOINT: http://localhost:8080/` configuration - no trailing slashes allowed!
Thanks to: https://stackoverflow.com/questions/54994392/how-do-i-set-up-an-envoy-proxy-in-minikube-for-a-grpc-service for helping me finally unlock things. 
In my attempt to fix things, I think I've ended up with a newer (maybe) envoy config and docker image. I still need to verify that this will work on k8s.
=> Fix docker compose for grpc-web

pkg/gds/admin/v2/csurf.go
This PR attempts to resolve the "no csrf token cookie in request" warning message. After a bit of research, our best guess is that it is an expiration issue, so we are slightly increasing the time allotment to see if it has an impact.
=> Increase expiration time for cookies

pkg/gds/admin.go, pkg/gds/admin/v2/api.go
CipherTrace wants to know when certificates are expiring, so I've added the expiration to the admin list API.
=> Adds certificate expiration to admin list API

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/api/v1/errors.go, pkg/bff/api/v1/errors_test.go
This PR defines the GDS BFF v1 API. The purpose of this package is to define the JSON data structures for requests and responses in the v1 API. It also implements a BFFClient which is used in testing and can also be used from a CLI implementation, though we have no plans to implement a CLI except for debugging and development. 
This package mirrors the `admin/v2` package, though it does omit the authentication and credentials components. The BFF epic currently has no authenticated endpoints, so I figured we'd save this until it was required for the GDS User UI.
=> Defines BFF API v1

pkg/bff/config/config.go, pkg/bff/config/config_test.go, pkg/gds/config/config_test.go
Implements the GDS BFF configuration including loading the configuration from the environment, some basic Gin server configs such as mode, log level, and bind addr, validation, mark, iszero, and some quick sanity-check tests. 
Blocked by #378
=> Implements GDS BFF Configuration

pkg/bff/mock/gds.go, pkg/bff/server.go, pkg/bff/server_test.go
This PR creates the BFF test suite and implements a Mock GDS for those tests. 
The goal of the BFF tests is test the expected contract between the UI and the BFF. Therefore the following decisions were made:
1. The BFF server is run on a live, local-loopback socket similar to the Go builtin [httptest.Server](https://cs.opensource.google/go/go/+/refs/tags/go1.17.8:src/net/http/httptest/server.go;l=28;drc=refs%2Ftags%2Fgo1.17.8;bpv=1;bpt=1). This allows end-to-end HTTP testing and also allows us to use the api.v1.BFFClient for tests, which should make developement and testing simpler. To ensure that this is possible, instead of implementing `ListenAndServe`, we've implemented separate `Listen` and `Serve` steps so that we can get the URL of the server and create the client in tests.
2. …
=> BFF Tests and Mock GDS

cmd/bff/main.go, pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/mock/gds.go, pkg/bff/server.go, pkg/bff/server_test.go, pkg/bff/status.go, pkg/bff/status_test.go
Implements the Status endpoint and our first BFF API Tests that interact with the GDS nodes.
TODO:
=> Status Endpoint

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/gds.go, pkg/bff/server.go, pkg/bff/status.go
This PR implements the BFF Lookup endpoint. The endpoint makes parallel Lookup requests to the GDS endpoint and returns an array of results marshaled directly from the `LookupReply`. It can return 1 or maybe 2 results (though 2 would be an unusual result); the response contains a `registered_directory` field to identify which directory the record came from. If no results are returned, a 404 is returned; if both GDS servers error, a 500 is returned. If only one errors, the response from the other is sent back and the error is logged.
=> BFF Lookup Endpoint

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/gds.go, pkg/bff/gds_test.go, pkg/bff/server.go, pkg/gds/emails/client.go, pkg/gds/emails/emails.go, pkg/gds/emails/emails_test.go
Implements the initial verify email endpoint for the 1.4 GDS and BFF by directing the user to a URL that contains a `registered_directory` param so that the BFF can identify the directory to forward the request to. 
This PR contains both the endpoint implementation and the tests. The files and mechanisms changed should be similar to the Register endpoint. 
TODO:
=> BFF Verify Contact Endpoint

pkg/gds/admin.go, pkg/gds/store/leveldb/leveldb.go, pkg/gds/store/trtl/trtl.go
This PR fixes some v1.3.1 constraint issues and 500 error handling that are needed in order to do some VASP-specific certificate management before the release.
Tasks performed:
=> Hotfix: 500 errors and website uniqueness

go.mod, go.sum, pkg/bff/server_test.go, pkg/bff/status_test.go, pkg/gds/emails/emails_test.go, pkg/gds/mock.go, pkg/gds/service_test.go, pkg/gds/store/leveldb/leveldb_test.go, pkg/gds/store/trtl/trtl_test.go, pkg/gds/tokens/tokens_test.go, pkg/trtl/mock.go, pkg/trtl/server_test.go, pkg/utils/logger/testing.go
This PR adds two utilities to our `pkg/util/logger` package:
1. `Testing` - sets the logger to use the `testing.T` logger
2. `Discard` - sets the logger to discard all output 
The logger package tracks the original logger and has a `Reset` functionality to cleanup after the test. 
Right now I've updated the test suites to use `Discard` in `SetupSuite` and to `Reset` in `TearDownSuite` -- for this `ConsoleLog` _must_ be false, otherwise the discard logger is overridden. This significantly reduces the amount of logging output during tests and will hopefully make it easier for us to figure out where tests are failing and handle them.
=> Reduce Test Logging Output

.env.template, cmd/certs/main.go, containers/docker-compose.yaml, pkg/bff/config/config.go, pkg/bff/config/config_test.go, pkg/bff/db/db.go, pkg/bff/server.go, pkg/bff/server_test.go, pkg/bff/status_test.go, pkg/gds/backup.go, pkg/gds/backup_test.go
This PR implements a database configuration for BFF to connect to trtl, implements a stub `bff/db` package for the BFF to interact with trtl, and implements a mock trtl connecting to a temporary directory leveldb for testing.
=> Connect BFF to Trtl

.github/workflows/containers.yaml
When tagging v1.3 a while back we received some errors in the GitHub workflow because our semantic version pattern was not actually valid. This changes the patterns to match some of the templates in the documentation here: 
https://github.com/docker/metadata-action#typesemver
=> sc-3825 fix semantic version pattern

cmd/gds/main.go, pkg/gds/interceptor.go, pkg/gds/store/trtl/iterator.go, pkg/gds/store/trtl/iterator_test.go
Fixes a panic that occurred when `trtl` was running when the `gds` server started, but came down after bootup. Adds tests for the panic case and also adds panic recovery so that the node doesn't come down even when it panics.
=> Fixes panic when trtl becomes unavailable and adds panic recovery

web/gds-user-ui/src/components/NameIdentification/index.tsx, web/gds-user-ui/src/components/ui/SelectFormControl/index.tsx
Allow FormHelperText prop on SelectFormControl component to display JSX Element rather than a String and format the content to display the link
=> allow FormHelperText prop to display jsx element

.env.template, containers/docker-compose.yaml, pkg/bff/config/config.go, pkg/bff/config/config_test.go, pkg/bff/gds.go, pkg/bff/server.go
sc-5100: This adds a few more environment variables for configuring sentry performance tracking and adds some instrumentation to the bff request handlers to track performance, if enabled.
=> sc-5100 bff performance tracking

web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx, web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx, web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx, web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx, web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx, web/gds-user-ui/src/index.css, web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
Create two columns in Details cards on "Submit & Review" page
This needs to be two uniform columns. We want the same column width across all cards so that when the user scrolls down, the information does not "zig zag" back and forth (along with the user's eyes).
After filling each steps of certificate registration, you can see on Review page that all columns are now uniform
=> sc-5268 Create two columns in Details cards on "Submit & Review" page

web/gds-user-ui/src/components/Section/VaspVerification.tsx
SC-5273: Fix Getting Started button not being close to the footer
=> SC-5273: Fix Getting Started button not being close to the footer

pkg/bff/auth/auth.go, pkg/bff/auth/csrf.go, pkg/bff/auth/csrf_test.go, pkg/bff/auth/errors.go, pkg/bff/users.go
Adds double cookie CSRF protection to the BFF middleware. The login endpoint also now sets double cookies that the UI must respect to prevent CSRF attacks. The CSRF protection will be applied to all `POST` endpoints to prevent malicious websites from cross-site forgery. 
We do have an implementation of this middleware for the Admin API - but this implementation is BFF-specific and is perhaps a bit stronger than the Admin implementation. It may be worth it to review the admin implementation at some point. 
SC-6407
=> BFF CSRF Middleware

pkg/bff/announcements.go, pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/db/announcements.go, pkg/bff/db/announcements_test.go, pkg/bff/db/db.go, pkg/bff/db/db_test.go, pkg/bff/db/errors.go, pkg/bff/db/testdata/announcements.json, pkg/bff/server.go, pkg/gds/members/v1alpha1/members.pb.go, pkg/trtl/pb/v1/trtl.pb.go, proto/trtl/v1/trtl.proto
This goal of this PR was to add a `GET /v1/announcements` endpoint to return network announcements for the dashboard. The design requested that we store these announcements in the BFF database. I extended the work for this to include a `POST /v1/announcements` endpoint to allow TRISA admins to create network announcements to display on the dashboard. This further required me to create the `create:announcements` permission in Auth0 and the "TRISA Admins` role so that only admins can create announcements. 
As I got into the code I realized that we aren't fully using the database module quite yet, so I had to put in some effort to exploring how we utilize the database. 
I came up with the idea of "Collections" which are like the GDS `Store` object that allow you to interact with a specific …
=> GDS BFF Network Announcement Endpoint

containers/auth0-debug/Dockerfile, containers/docker-compose.yaml, web/auth0-debug/serve.py
Adds the auth0-debug web application to docker compose to make it easier to get access tokens for development and testing. This included:
1. Updating the auth0 config from http://localhost:3000 to http://localhost:3003 to deconflict with other docker compose ports
2. Changing the default port in `serve.py` from 3000 to 30003
3. Creating a Dockerfile
4. Creating the service in our docker compose file. 
Verify that I've included everything needed to run the auth0 debugger locally. To run it you can:
```
$ docker compose -f ./containers/docker-compose.yaml --profile=auth0 build
$ docker compose -f ./containers/docker-compose.yaml --profile=auth0 up
```
Then go to http://localhost:3003 -- and you should be able to use it.
=> Add Auth0 Debugger to Docker Compose

containers/local.sh, pkg/bff/api/v1/api.go, pkg/bff/api/v1/client_test.go, pkg/bff/gds.go, pkg/bff/gds_test.go
Modifies the LookupReply to an object `{"testnet": {}, "mainnet": {}}` rather than an array of results `{"results": []}` 
I also added a `containers/local.sh` script to make it easier to run docker compose. Usage is as follows:
Run `docker system prune --all`:
```
$ ./containers/local.sh clean
```
Build the containers:
```
$ ./containers/local.sh build
```
Run the containers:
```
$ ./containers/local.sh up
```
@masskoder will this enable you to do what you need to do?
@pdeziel can you think of any other places this change might have an effect?
I did try to run docker compose locally to get you a snapshot of what the data might look like, but I also need #611 to be merged to run docker compose.
=> BFF Lookup Endpoint Refactor

pkg/gds/certs.go, pkg/gds/certs_test.go
This adds some tests to verify that the cert manager state checks implemented in SC-6508 correctly reject certificate requests when the VASP is in the wrong state.
SC-7518
Unit tests should pass
=> certificate vasp state tests

pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/server.go
This changes the method on the save registration endpoint from POST to PUT to be more inline with what it does, since we use it to both create and update the form.
SC-7641
Unit tests should pass.
=> change save registration endpoint to PUT

web/gds-user-ui/src/components/LanguagesDropdown/index.tsx
sc-7566 GDS User UI : Hide other languages that don't have translation content yet
Until we get the other content, we only need to keep the language that has full translations.
=> sc-7566 GDS User UI : Hide other languages that don't have translation content yet

web/gds-user-ui/src/components/Section/SearchDirectory.tsx
Sc-7570:  add missing N/A value for a null testnet response
Sc-7570:  add missing N/A value for a null testnet response
=> Sc-7570:  add missing N/A value for a null testnet response

pkg/gds/certman/certs.go, pkg/gds/certman/certs_test.go, pkg/gds/models/v1/models.go, pkg/gds/models/v1/models_test.go
This adds a check before we create the certificate request for reissuance so that we don't end up creating multiple requests for the same VASP when the reissuance auto triggers.
=> Add check to prevent double certreq creation

pkg/gds/certman/certs_test.go, pkg/gds/emails/client_test.go
This adds some assertions in the GDS email client and certman tests to ensure that reissuance-related emails are not sent twice.
SC-8903
Unit tests should pass.
=> Duplicate email tests

web/gds-user-ui/src/modules/dashboard/certificate/lib/basicDetailsValidationSchema.ts
sc-9037 GDS User UI : disallow users to select a future date on Date of Incorporation / Establishment
https://app.shortcut.com/rotational/story/9037/gds-user-ui-disallow-users-to-select-a-future-date-on-date-of-incorporation-establishment
=> sc-9037 GDS User UI : disallow users to select a future date on Date of Incorporation / Establishment

.github/workflows/tests.yaml
Updates the test workflows which will hopefully improve test times and ensure that CodeCov doesn't take forever.
I'll merge this if everything looks ok, no need for review.
- N/A
=> Update Test Workflow

cmd/reissuer/build.sh, cmd/trtl/main.go
This PR is required for SC-9227. @masskoder created an account on production but asked me to delete it. It is straight forward to delete his user from Auth0 via their UI, but this leaves a disconnected `organization` in the trtl database that used to be associated with the user. In an effort to keep the BFF database clean, I wanted to delete the organization associated with the user account. Unfortunately, the `trtl` CLI program had some bugs in it that did not allow me to do this easily - this PR fixes those bugs. 
The primary issue is that the keys for the `organizations` are the UUID bytes (not a string) so you can't specify the key on the command line to delete it. The `trtl` command had utilities for base64 encoded keys, but they were not consistent (e.g. not on the `db:put` and …
=> Fix trtl CLI bugs

web/gds-user-ui/src/components/BasicDetail/index.tsx, web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx
sc-9268 Remove Shaded Line on Overview page
https://app.shortcut.com/rotational/story/9268/remove-shaded-line-on-overview-page
=> sc-9268 Remove Shaded Line on Overview page

pkg/bff/gds_test.go, pkg/bff/members.go, pkg/bff/members_test.go
This fixes a bug that existed in a code path that was untested in the bff overview handler. We were constructing a member details response for mainnet but not testnet which made the the response a bit inconsistent for the frontend. This removes some logic to make the response more consistent and adds a test case to make sure the code path is covered.
SC-9299
In the case where the user is not associated with a mainnet VASP, the overview endpoint should now return an empty string for the `status` field in the `MemberDetails` response for mainnet instead of `NO_VERIFICATION`.
=> Fix inconsistent overview response

pkg/gds/interceptor.go
This fixes a masked error that can occur due to the panic handling logic in the GDS unary interceptor. We use the `panicked` flag to determine if a panic has occurred in the gRPC handler, and there was a path in the interceptor where this flag was not getting set, which could result in a "false" panic being generated and the error not being captured.
SC-9632
=> Fix masked error

web/gds-user-ui/src/application/routes/index.tsx, web/gds-user-ui/src/application/routes/routes.ts
Redirect /certificate/registration to /guide
https://app.shortcut.com/rotational/story/9617/redirect-certificate-registration-to-guide
=> sc-9617: Redirect to guide page 

web/gds-user-ui/src/components/SectionStatus/SavedSectionStatus.tsx, web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx, web/gds-user-ui/src/components/TestnetProgress/InvalidFormPrompt.tsx, web/gds-user-ui/src/components/TestnetProgress/__tests__/InvalidFormPrompt.spec.tsx, web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
sc-6823 GDS UI : make the stepper component label responsive on a small screen
=> sc-6823 GDS UI : make the stepper component label responsive on a small screen

web/gds-admin-ui/package.json, web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BasicDetailsDropdown.js, web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Print.js, web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/Print.spec.js, web/gds-admin-ui/yarn.lock
sc-10115 Print view does not work
https://app.shortcut.com/rotational/story/10115/print-view-does-not-work
https://user-images.githubusercontent.com/54010836/196679286-c465956c-4000-41ac-a293-dcc651ae6f66.mov
=> sc-10115:  Fix Print view issue

cmd/reissuer/build.sh, cmd/reissuer/main.go, pkg/gds/certman/certs.go, pkg/models/v1/models.go, pkg/models/v1/models_test.go, pkg/models/v1/testdata/vasp.json
We had an issue with a TRISA TestNet registration today where Sectigo rejected the domain name causing multiple critical alerts to trigger. To remediate the situation we put the registration back to "PENDING_REVIEW". This PR contains the helper script in the `reissuer` command that allowed us to do that.
While working on that, I noticed that the batch names had an extra `")"` at the end, so I fixed that minor typo, and since I was there, I also fixed the typo where Certman saves the VASP every day even if it hasn't been changed (causing the last updated timestamp to be unusable). 
Fixes SC-10097
Fixes SC-10325
For the most part you can ignore the helper command in `reissuer` -- we've already run this command and it worked. The real question is about certman. Is the `updateRequired` bool …
=> Certman Bug Fixes and Helper Utility

web/gds-admin-ui/src/components/Table.js
sc-10101 Preserve sort order in the VASPs list
https://app.shortcut.com/rotational/story/10101/preserve-sort-order-when-the-user-goes-between-the-list-view-and-the-detail-view
https://user-images.githubusercontent.com/54010836/197527526-c7512047-c2e4-40ea-90e8-a2f49f48da8d.mov
=>  sc-10101 Preserve sort order in the VASPs list

web/gds-user-ui/src/assets/TRISA-GDS.svg, web/gds-user-ui/src/components/Header/LandingHeader.tsx, web/gds-user-ui/src/components/ui/Logo.tsx
fix: sc-9875 increase landing logo's size
=> fix: sc-9875 increase landing logo's size

.vscode/settings.json, pkg/gds/admin.go, pkg/gds/admin/v2/api.go, pkg/gds/admin_test.go, pkg/gds/certman/certs_test.go, pkg/gds/fixtures/fixtures.go, pkg/gds/fixtures/fixtures_test.go
This adds a reissuance timestamp to the VASP snippet. This is required for the frontend to be able to filter/order VASPs by certificate reissuance date.
=> Add reissaunce timestamp to vasp snippet

pkg/bff/users.go
This fixes an Auth0 related bug on the Login endpoint. When we remove and assign user roles, we need to make sure that we're passing a non-empty list to the management API so that we don't trip an error.
SC-11196
=> Avoid Auth0 role management 400

pkg/bff/organization.go, pkg/bff/organization_test.go
This fixes a bug where the user tries to switch organizations and gets a 401 error due to not being a collaborator on the organization. The fix is to add them as a collaborator when they create the organization.
SC-11488
=> Add user as collaborator on CreateOrganization

pkg/bff/users.go, pkg/bff/users_test.go
This fixes a bug where the collaborator details weren't showing up on the collaborators page after a user is invited due to the Auth0 user id being missing from the collaborator record. The fix is to update the user id when the user logs in.
SC-11826
=> Fix missing auth0 user id

web/gds-user-ui/src/components/Sidebar/MobileNav.tsx
sc-11788 Hide 'Switch Acct' option when user is not a TSP
https://app.shortcut.com/rotational/story/11788/hide-switch-acct-option-when-user-is-not-a-tsp
=> sc-11788 Hide `Switch Acct` option when user is not a TSP

pkg/gds/gds.go, pkg/gds/gds_test.go
This PR adapts the GDS Search and Lookup RPCs to only returned VERIFIED records. The VerificationStatus RPC still returns any state, but you must have the ID or common name for this lookup so it is safer than Search and Lookup. 
The change is pretty simple, just a couple of lines of code in the Search and Lookup RPCs. The tests had to be radically altered however. I used a subtest method to isolate our different tests. Are the tests we have sufficient?
=> Can only search and lookup verified records

web/gds-user-ui/src/application/api/user.ts, web/gds-user-ui/src/application/store/selectors/user.ts, web/gds-user-ui/src/components/CertificateReview/index.tsx, web/gds-user-ui/src/components/UserProfile/ChangeNameForm.tsx, web/gds-user-ui/src/components/UserProfile/ChangeNameModal.tsx, web/gds-user-ui/src/components/UserProfile/__tests__/ChangeNameForm.spec.tsx, web/gds-user-ui/src/components/UserProfile/__tests__/UserDetails.spec.tsx, web/gds-user-ui/src/components/UserProfile/index.tsx, web/gds-user-ui/src/components/UserProfile/useCreateUserName.ts, web/gds-user-ui/src/modules/auth/login/user.slice.ts, web/gds-user-ui/src/modules/dashboard/profile/index.tsx, web/gds-user-ui/src/utils/auth.ts, web/gds-user-ui/src/utils/auth0.helper.tsx, web/gds-user-ui/src/utils/constants.ts, web/gds-user-ui/src/utils/permission.ts, web/gds-user-ui/src/utils/react-query.ts
This allows the users to update their fullname.
=> sc-10525: change name implementation

pkg/bff/users.go
This addresses an issue that can happen when a user has the same email address on multiple accounts (e.g. an email account and a Google account) and another user tries to invite them. We do a search of Auth0 to fetch the invited user's record, but this can return multiple results. We were previously returning an error, but the ambiguity doesn't really matter too much in this case since nothing official happens until the invited user logs in.
This removes the error in place of just using the first available record returned from Auth0. The only difference is that we may or may not include the user's real name in the invite email.
The long term solution however is to probably have a way for users to link accounts, but that is a much larger effort.
SC-11849
Describe how reviewers can test …
=> Change duplicate email error to warning

cmd/bffutil/main.go
Adds a `bffutil` command to create a new BFF organization from a GDS registration that was created before the BFF existed. This will allow users to login and manage those older registrations.
Fixes SC-11993
Review to ensure that the organization is created correctly. Do we want a different output format (CSV, JSON)?
=> Migrate old GDS records to BFF Organizations

web/gds-admin-ui/src/pages/app/details/contact/Contact.js, web/gds-admin-ui/src/pages/app/details/contact/__tests__/contact.spec.js, web/gds-admin-ui/src/pages/app/details/contact/index.js
sc-10109 Warning text color is too hard to read
https://app.shortcut.com/rotational/story/10109/warning-text-color-is-too-hard-to-read
=> sc-10109 Warning text color is too hard to read

pkg/bff/auth/metadata.go, pkg/bff/auth/metadata_test.go
This modifies the `AddOrganization` and `RemoveOrganization` methods on the `AppMetadata` struct so that ordering is preserved in the list for the org IDs in a user's app metadata. This is primarily a performance improvement which is relevant to TSPs who exist in many organizations at once, since a binary search can be used (via the go `sort` package) rather than iterating through the entire list.
This change will require a migration to sort the organization IDs in Auth0 (currently they are unordered).
The existing methods should still operate as described in the docstring with the new sort code.
=> Sorted appdata organizations

pkg/gds/certman/certs_test.go
This adds leveldb testing to the certman test suite. Previously the certman tests only tested with trtl as the underlying database. This creates another test suite which runs the same certman tests, but with leveldb as the underlying store instead.
We were already using the `store` abstraction for certman so this turned out to be pretty simple.
There should now be two separate tests suites when we run the certman tests, one for leveldb and the other for trtl.
=> Certman leveldb tests

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/docs/docs.go, pkg/bff/docs/swagger.json, pkg/bff/docs/swagger.yaml, pkg/bff/organization.go, pkg/bff/organization_test.go
This adds pagination to the `ListOrganizations` BFF endpoint. It now accepts two query parameters to control the pagination: `page` and `page_size`, similar to how pagination is implemented for `ListVASPs` on the Admin API. This will allow the user UI frontend to load pages of organizations individually to avoid the list filling up the entire page.
Callers should be able to use the query params in the `ListOrganizations` request to control the paginated response.
=> Add pagination to list orgs

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/auth/user.go, pkg/bff/docs/docs.go, pkg/bff/docs/swagger.json, pkg/bff/docs/swagger.yaml, pkg/bff/organization.go, pkg/bff/organization_test.go, pkg/bff/server.go
This adds an update organization endpoint to the BFF API. This takes as input the same schema as `CreateOrganization` but only updates the provided fields.
SC-11814
The client should be able to update the name and domain on existing organizations with the new endpoint.
=> BFF update organization

pkg/bff/api/v1/api.go, pkg/bff/docs/docs.go, pkg/bff/docs/swagger.json, pkg/bff/docs/swagger.yaml, pkg/bff/organization.go, pkg/bff/organization_test.go
This adds a basic name filter to the `ListOrganizations` endpoint on the BFF, to enable the GDS user UI to implement a "search" feature where the user can type in an organization name rather than going through the pages.
=> Name filter for org list

cmd/gdsutil/main.go, cmd/trtl/main.go, cmd/trtlsim/main.go, pkg/trtl/namespaces.go, pkg/trtl/replica/replica.go, pkg/trtl/replica/sync.go, pkg/utils/wire/wire.go
Adds Contacts to wire.Namespaces (as noted in the shortcut story, code sections where it is unclear if updates are needed are marked with the comment: "// ???")
=> sc-14482: Create NamespaceContact

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/docs/docs.go, pkg/bff/docs/swagger.json, pkg/bff/docs/swagger.yaml, pkg/bff/gds.go, pkg/bff/gds_test.go, pkg/bff/server.go
This adds a BFF endpoint to delete a registration form, either by requesting a specific step or deleting the entire form by default. When a form step is deleted, the values are reset to the defaults and no validation errors are returned.
SC-17560
=> Delete registration form endpoint

pkg/bff/models/v1/errors.go, pkg/bff/models/v1/registration.go, pkg/bff/models/v1/registration_test.go
This fixes two registration form validation issues:
1. Only one of testnet/mainnet TRISA details are required (SC-17594)
2. VASP categories is not a required field (SC-17596)
=> Fix network details and vasp category validation

web/gds-user-ui/src/components/CertificateReview/LegalPersonReviewDataTable.tsx, web/gds-user-ui/src/components/RegistrationForm/InvalidFormPrompt.tsx
Shows the `Reg Authority` in Section 2 on the Review page only if `LEI` isn't the selected Identification Type. This should prevent the error seen in the screenshot below from appearing:
Also, fixes error where the `Unsaved Changes` modal doesn't display button text. The previous fix didn't work in staging.
https://www.awesomescreenshot.com/video/17930045?key=fa619095c4864f67d9944e01bbe942e8
Note: I noticed that the `Unsaved Changed` modal doesn't display if the step before it is displaying as `In Progress`. I included this in the video. I didn't attempt to fix because I believe other changes are being made to the progress bar and am not sure if that will resolve the issue.
=> Adds conditional to reg authority and updates unsave modal text

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/members.go, pkg/bff/members_test.go, pkg/bff/server.go, pkg/bff/testdata/mainnet/list_reply.json, pkg/bff/testdata/testnet/list_reply.json
Adds a BFF endpoint `GET /v1/members` that available to verified VASPs to request the list of other verified VASPs in the specified directory. 
Requests to either the TestNet or MainNet return a list of paginated members from that directory service.
=> BFF Members List RPC

web/gds-user-ui/src/modules/dashboard/member/__mocks__/index.ts, web/gds-user-ui/src/modules/dashboard/member/memberType.ts, web/gds-user-ui/src/modules/dashboard/member/utils.ts
Changes `Status` type to a `number` instead of a `string`.
Fixes SC-18747
=> Updates status type to number

pkg/gds/members.go, pkg/gds/members_test.go
Ensures that only the name, email, and phone number of the administrative, technical, legal, and billing contacts are returned in a Member Detail RPC. This is a follow on from #1072 (SC-18635) to update the GDS to participate in the request.
Fixes SC-18767.
=> Ensure GDS Member Detail returns Contacts

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client_test.go, pkg/bff/members.go, pkg/bff/members_test.go, pkg/bff/testdata/mainnet/details_reply.json, pkg/bff/testdata/testnet/details_reply.json
This rewires the VASP summary in the member details response so that protobuf enums show up as strings in the response rather than the number.
=> Rewire VASP summary

pkg/bff/api/v1/api.go, pkg/bff/api/v1/client.go, pkg/bff/api/v1/client_test.go, pkg/bff/gds.go, pkg/bff/gds_test.go, pkg/bff/server.go
This PR resolves SC-20290 which asked to add a new stub BFF endpoint that the front end will use to display the activities that take place on TestNet and MainNet (Search, Lookup).
=> Added stub network activity data bff endpoint

go.mod, go.sum, pkg/gds/certman/certs.go, pkg/gds/certman/certs_test.go, pkg/gds/config/config.go, pkg/gds/config/config_test.go, pkg/models/v1/models.go
This adds webhook delivery functionality to certman. If the VASP has a webhook URL then certman will attempt to deliver pkcs12 passwords and certificates by webhook, in addition to emailing them. If the VASP has the `NoEmailDelivery` flag set then the password and certificate emails are not sent, unless the webhook delivery fails.
Certman now has a backoff configuration for webhook delivery. If the webhook request is unsuccessful then by default it retries after the backoff period up to the maximum number of retries before giving up.
Retry logic should be checked for correctness and we may need to tag the trisa repo to ensure that the dependency is stable.
=> Add webhook delivery to certman

web/gds-user-ui/src/components/Section/SearchDirectory.tsx
- Removes autofocus from the search directory input to prevent home page from scrolling down to the bottom after loading and refresh.
- Removes capitalization from the list results. 
- Switches positions of the `Mainnet` and `Testnet` search directory results.
Note: In video below, some of the list results are capitalized. This is because they were capitalized during creation while in development, so this is how they're returned from the BE.
https://www.awesomescreenshot.com/video/23771981?key=1b2b576abb0c58df8af5bb670056267a
=> Removes autofocus and capitalization from search directory

web/gds-user-ui/src/components/Collaborators/index.tsx, web/gds-user-ui/src/components/Sidebar/index.tsx, web/gds-user-ui/src/modules/dashboard/member/index.tsx
Sets the overflow value to auto to remove empty scrollbars that made extra whitespace appear in the right and bottom margins.
Below are links to images to provide examples of how the whitespace currently appears on all pages:
https://www.awesomescreenshot.com/image/45224195?key=efb925603878b13acfca7cec44967126
https://www.awesomescreenshot.com/image/45224206?key=7915d0b8867061ca132ca5a3e2cfbbe7
https://www.awesomescreenshot.com/video/23798456?key=f3d65d6eda9b16f7c0bbf99a82e9b9ca
=> Removes empty scrollbars and sets overflow value to auto

web/gds-user-ui/src/components/LanguagesDropdown/index.tsx, web/gds-user-ui/src/components/Metrics/index.tsx, web/gds-user-ui/src/components/Sidebar/MobileNav.tsx
Adjusts spacing and margin on the `Navbar` to prevent the language select element from spilling over onto the `Sidebar`. 
The issue can be seen in the first few seconds of the following video: https://www.awesomescreenshot.com/video/23774299?key=8343b2d1c5c9b0c219a1369f7ec898c4
https://www.awesomescreenshot.com/video/23929787?key=1af664af547cfbd087533fcdaba31248
=> Adjusts spacing between topbar elements to prevent spill over

web/gds-user-ui/.linguirc, web/gds-user-ui/src/locales/de/messages.po, web/gds-user-ui/src/locales/en/messages.po, web/gds-user-ui/src/locales/es/messages.po, web/gds-user-ui/src/locales/fr/messages.po, web/gds-user-ui/src/locales/ja/messages.po, web/gds-user-ui/src/locales/pt/messages.po, web/gds-user-ui/src/locales/zh/messages.po
Add Spanish and Portuguese to locales in `lingui` config. Also, runs an extraction to create `.po` files where translations will be added for both languages.
=> Add Spanish and Portuguese to lingui locales

web/gds-user-ui/src/utils/auth0.helper.ts, web/gds-user-ui/src/utils/axios.ts
Fix to resolve `Cannot read properties of null` TypeError by adding optional chaining `(?)` to verify that the result isn't `null` or `undefined` before attempting to access the `accessToken` value.
=> Add optional chaining to resolve null error

web/gds-user-ui/src/components/Collaborators/AddCollaborator/AddCollaboratorForm.tsx, web/gds-user-ui/src/components/Collaborators/EditCollaborator/EditCollaboratorModal.tsx, web/gds-user-ui/src/components/Collaborators/EditCollaborator/useUpdateCollaborator.ts, web/gds-user-ui/src/utils/axios.ts
Fix the following error, `Error: Objects are not valid as a React child` , by replacing a custom toast component with the Chakra UI toast component.
The changes also ensure the `Add Collaborator` modal completely closes after a user experiences an error and displays the error message provided from the BE. Error messaging was updated in the `Edit Collaborator` form as well to resolve an error caused by updating the `axiosInstance` to return error responses.
Note: The inspector was open while recording the video below to confirm that the error messages didn't appear in the console. This is why the modal may appear to not fit the screen.
https://www.awesomescreenshot.com/video/24167192?key=96d5767d73b78c0b8adda5a190d63267
=> Replace custom toast component

web/gds-user-ui/src/components/TrixoQuestionnaire/index.tsx
Fix error in `TRIXO` form so that the page will reload and remove data after users confirm that they'd like to reset the form.
https://www.awesomescreenshot.com/video/24336690?key=b694f17e7dc16e7c8e4e344e3d7ea8fe
=> Fix reset error in TRIXO form

web/gds-user-ui/src/components/AddressForm/index.tsx, web/gds-user-ui/src/components/Addresses/AddressList.tsx, web/gds-user-ui/src/constants/address.ts, web/gds-user-ui/src/modules/dashboard/certificate/lib/defaultValues.ts
Creates a constant for the address type enum sent to the backend and replaces strings with constants in the address form.
=> Add constant for address type codes and & update strings with constants

web/gds-user-ui/src/components/CertificateReview/index.tsx, web/gds-user-ui/src/components/ReviewSubmit/index.tsx, web/gds-user-ui/src/hooks/useCertificateStepper.tsx, web/gds-user-ui/src/modules/dashboard/certificate/lib/trixoQuestionnaireValidationSchema.ts, web/gds-user-ui/src/modules/dashboard/registration/hooks/useSubmissionStatus.ts
This fixes a bug that could cause the registration confirmation modal to appear multiple times. Another bug that allowed users to click the registration form's submit button if they'd previously submitted a registration has also been fixed. A warning box consistently appears on the registration page if a user has only completed all fields for one network.
Video:
https://www.awesomescreenshot.com/video/25218910?key=e0a0cf29a46669ede18adcf003a5a308
Images of warning box:
https://www.awesomescreenshot.com/image/46253857?key=08462d29f0ac4e956ff025991e6c8161
https://www.awesomescreenshot.com/image/46253859?key=30e2e70a915be77ad9710bc2970424ad
=> Fix bug displaying registration confirmation modal multiple times

web/gds-user-ui/src/hooks/useFetchAttention.tsx, web/gds-user-ui/src/modules/dashboard/certificate/service/certificateService.ts
Adds optional chaining to the `useFetchAttention` hook and `certificateService` service to resolve `undefined` errors.
Fixes SC-24169 & SC-24170
=> Add optional chaining to resolve undefined errors

web/gds-user-ui/src/components/ReviewSubmit/index.tsx
Sets the stepper status to complete after a user submits the registration form.
https://www.awesomescreenshot.com/video/25370460?key=2b8264fa9105338e9f47cf1ebeb01572
=> Set review stepper state to complete after user submits registration

web/gds-user-ui/src/components/Footer/LandingFooter.tsx, web/gds-user-ui/src/components/Header/LandingHeader.spec.tsx, web/gds-user-ui/src/components/Header/LandingHeader.tsx, web/gds-user-ui/src/components/Section/AboutUs.tsx, web/gds-user-ui/src/components/Section/IntegrateAndComply.tsx, web/gds-user-ui/src/components/Section/JoinUs.tsx, web/gds-user-ui/src/components/Section/VaspVerification.tsx, web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap, web/gds-user-ui/src/components/Section/__tests__/__snapshots__/VaspVerification.spec.tsx.snap, web/gds-user-ui/src/locales/de/messages.po, web/gds-user-ui/src/locales/en-dh/messages.po, web/gds-user-ui/src/locales/en/messages.po, web/gds-user-ui/src/locales/es/messages.po, web/gds-user-ui/src/locales/fr/messages.po, web/gds-user-ui/src/locales/ja/messages.po, web/gds-user-ui/src/locales/pt/messages.po, web/gds-user-ui/src/locales/zh/messages.po, web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap
This PR updates links navigating users to trisa.dev back to trisa.io. It also updates test snapshots and `.po` files.
=> Change trisa.dev links to trisa.io

web/gds-user-ui/src/components/NeedsAttention/index.tsx
This PR adds optional chaining to check if a property is undefined before attempting to access a value that will be passed to the `Alert` component as a prop.
The change should resolve the following error: `Cannot read properties of undefined (reading 'colorScheme')`.
=> Add optional chaining to prevent undefined error
