trisacrypto/directory

web/src/App.js
web/src/components/Registration.js
web/src/components/TRIXO.js

Enhances the GDS UI registration form with local storage so that the
form persists between browser tabs and when the browser is reloaded,
making the long form easier to fill out. It also adds a reset button the
summary page to clear the form out and start over.
Additionally adds a download button to download the JSON data for the
form and a load button to load downloaded data back into the form. This
makes the form usable for editing registration forms before the database
is live.
TODO:

WIP: GDS UI Local Storage and Load/Download

---

go.sum
pkg/gds/models/v1/models.go

This PR fixing the marshalling of the extra attribute using `anypb`.

Fix pb marshalling for the extra attribute

---

web/src/components/LookupResults.js
web/src/components/Registration.js
web/src/components/TRIXO.js

Fixes the following front end bugs caught in QA:
- On registration validation error, submit button stays disabled
- Typos in TRIXO form and confirmation modal
- Uncaught exception when no identity ceritificate is present

Front-End QA Items

---

containers/gds-testnet-ui/nginx.conf
containers/gds-ui/nginx.conf
pkg/gds/admin.go
pkg/gds/backup.go
pkg/gds/certs.go
pkg/gds/gds.go
pkg/gds/logger/logger.go
pkg/gds/replica.go

Updates logging severities to correct levels for monitoring and alerts.
Co-authored with @rebeccabilbro

Logging Severity Audit

---

web/gds-admin-ui/.gitignore
web/gds-admin-ui/env.example
web/gds-admin-ui/package.json
web/gds-admin-ui/src/constants/menu.js
web/gds-admin-ui/src/helpers/api/apiCore.js
web/gds-admin-ui/src/layouts/LeftSidebar.js
web/gds-admin-ui/src/pages/app/dashboard/Statistics.js
web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/pages/app/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/dashboard/index.js
web/gds-admin-ui/src/redux/dashboard/actions.js
web/gds-admin-ui/src/redux/dashboard/constants.js
web/gds-admin-ui/src/redux/dashboard/reducers.js
web/gds-admin-ui/src/redux/dashboard/saga.js
web/gds-admin-ui/src/redux/reducers.js
web/gds-admin-ui/src/redux/sagas.js
web/gds-admin-ui/src/routes/index.js
web/gds-admin-ui/src/services/dashboard.js
web/gds-admin-ui/yarn.lock

feat: add dashboard page

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/assets/scss/custom/pages/_authentication.scss
web/gds-admin-ui/src/layouts/Footer.js
web/gds-admin-ui/src/pages/account/AccountLayout.js
web/gds-admin-ui/src/pages/account/Login.js
web/gds-admin-ui/src/routes/index.js
web/gds-admin-ui/yarn.lock

feat: add login page

---

cmd/gdsutil/main.go

In order to export the list of current VASPs, we need a tool that
exports CSV data without sensitive information. The previous `ldb:list`
functionality is a good candidate since it's summary text information
could be improved by a more readable output.
Fixes SC611

Updates ldb:list to CSV output

---

containers/docker-compose.yaml
pkg/gds/admin.go
pkg/gds/config/config.go
pkg/gds/config/config_test.go

Implements a configuration for CORS control of the Admin API. This will
allow us to more flexbily deploy the Admin UI on multiple domains while
restricting access necessary for credentials.

Implement Allowed Origins configuration

---

cmd/gdsutil/main.go
containers/docker-compose.yaml
pkg/gds/admin.go
proto/gds/models/v1/models.proto

A gdsutil script that reissues a certificate.

register:reissue

---

web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/utils/index.js

feat: Implement review speed Pie chart with summary endpoint

---

web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/pages/app/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/dashboard/TasksChart.js
web/gds-admin-ui/src/pages/app/dashboard/index.js

fix: vertical overflow in pending reviews makes it hard to use controls

---

web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/pages/app/dashboard/TasksChart.js

fix: timeline showing up blank

---

web/gds-ui/package.json
web/gds-ui/src/App.js
web/gds-ui/src/components/Lookup.js
web/gds-ui/src/components/NotFound.js
web/gds-ui/src/components/Registration.js
web/gds-ui/src/components/VerifyContact.js
web/gds-ui/src/lib/analytics.js
web/gds-ui/yarn.lock

Track the various routes navigated to in the GDS UI.

Add Google Analytics 4 Tracking

---

web/gds-ui/src/components/TopNav.js
web/gds-ui/src/components/select/LanguageSelect.js

This is a very simple language selection dropdown that has a flag and
the language code. I'm not sure it's the best, but it will do for now to
get the deployment going.

GDS UI: Implements Language Selection Dropdown

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js

fix: statuses badge display in VASP details

---

web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/assets/scss/app.scss
web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/pages/app/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/dashboard/index.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Geographic.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Name.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/NationalIdentification.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/pages/app/details/contact/index.js
web/gds-admin-ui/src/utils/index.js

feat: redirect a pending vasp to its details by clicking on the row

---

pkg/gds/admin.go
pkg/gds/admin/v2/api.go
pkg/gds/admin/v2/client_test.go
pkg/utils/pb.go
pkg/utils/pb_test.go

This PR unblocks @elysee15 by actually sending audit log data in the VASP Detail endpoint.

GDS Admin API: Audit Log in VASP Detail

---

cmd/trtl/main.go
pkg/gds/config/config.go
pkg/gds/service.go
pkg/trtl/config/config.go
pkg/trtl/config/config_test.go
pkg/trtl/namespaces.go
pkg/trtl/replica.go
pkg/trtl/trtl.go
pkg/trtl/trtl_test.go
pkg/utils/logger/level.go
pkg/utils/logger/level_test.go
pkg/utils/logger/logger_test.go

This PR implements a robust trtl configuration and configures trtl logging for service startup. It also generalizes some of the logging utilities and adds tests for them. Comments inline with the code.

TRTL: configuration and logging

---

pkg/gds/client/profile_test.go
pkg/gds/client/profiles.go
pkg/gds/client/profiles_test.go

This adds tests for the profiles management functionality.

sc-1529 add profiles tests

---

web/gds-admin-ui/src/__mocks__/contact.js
web/gds-admin-ui/src/__tests__/contact.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/constants/index.js
web/gds-admin-ui/src/pages/app/details/contact/Contact.js
web/gds-admin-ui/src/utils/index.js

fix: Contact Verification Bug

---

web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNote.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNoteForm.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNotes.js
web/gds-admin-ui/src/redux/review-notes/actions.js
web/gds-admin-ui/src/redux/review-notes/constants.js
web/gds-admin-ui/src/redux/review-notes/reducers.js

I figured out that the review note creation doesn't behave as I expected then I made this fix to make it work with redux correctly

fix: add review doesn't behave as expected

---

web/gds-admin-ui/src/pages/app/details/AuditLog.js
web/gds-admin-ui/src/pages/app/details/index.js

feat: add audit log

---

web/gds-admin-ui/src/pages/app/details/index.js

fix: Re-render VASP detail is issuing many API requests

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/components/Table.js
web/gds-admin-ui/src/helpers/api/apiCore.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNoteForm.js
web/gds-admin-ui/src/pages/app/details/index.js
web/gds-admin-ui/src/pages/app/lists/index.js
web/gds-admin-ui/src/redux/dashboard/actions.js
web/gds-admin-ui/src/redux/dashboard/saga.js
web/gds-admin-ui/src/redux/selectors/vasps.js
web/gds-admin-ui/src/services/vasps.js
web/gds-admin-ui/yarn.lock

fix: Filter VASP list via query param and UI controls

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/layouts/Default.js
web/gds-admin-ui/src/layouts/Footer.js
web/gds-admin-ui/src/layouts/LeftSidebar.js
web/gds-admin-ui/src/layouts/Menu.js
web/gds-admin-ui/src/layouts/Topbar.js
web/gds-admin-ui/src/layouts/Vertical.js
web/gds-admin-ui/src/pages/account/AccountLayout.js
web/gds-admin-ui/src/pages/app/dashboard/Statistics.js
web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/pages/app/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/dashboard/TasksChart.js
web/gds-admin-ui/src/pages/app/dashboard/index.js
web/gds-admin-ui/src/pages/app/details/AuditLog.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Geographic.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Name.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/NationalIdentification.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/EditReviewNote.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNote.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNoteForm.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNotes.js
web/gds-admin-ui/src/pages/app/details/index.js

fix: add propTypes validation to each components

---

web/gds-admin-ui/src/constants/trixo.js
web/gds-admin-ui/src/pages/app/details/TrixoForm.js
web/gds-admin-ui/src/pages/app/details/index.js
web/gds-admin-ui/src/utils/index.js

feat: TRIXO card

---

web/gds-admin-ui/src/__tests__/certificate-details.js
web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/components/FileInformationCard.js
web/gds-admin-ui/src/pages/app/details/CertificateDetails.js
web/gds-admin-ui/src/pages/app/details/TrixoForm.js
web/gds-admin-ui/src/utils/index.js

feat:  Certificate Card in VASP Detail

---

web/gds-admin-ui/src/__tests__/audit-log.spec.js
web/gds-admin-ui/src/__tests__/basic-details.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/components/FileInformationCard.js
web/gds-admin-ui/src/components/Table.js
web/gds-admin-ui/src/pages/app/lists/index.js
web/gds-admin-ui/src/utils/index.js

feat: Select what should be exported from VASP list

---

pkg/gds/gds.go
pkg/gds/gds_test.go

This adds a test for the GDS Verification RPC.

sc-2189 verification RPC test

---

pkg/trtl/honu_test.go
pkg/trtl/trtl_test.go

This PR resolves sc-2098, doing a bit of cleanup on the environment variables for the trtl & honu tests.

Make trtl region and pid test vars

---

web/gds-admin-ui/src/__tests__/basic-details.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/assets/scss/custom/plugins/_react-select.scss
web/gds-admin-ui/src/components/TopbarSearch.js
web/gds-admin-ui/src/redux/actions.js
web/gds-admin-ui/src/redux/autocomplete/actions.js
web/gds-admin-ui/src/redux/autocomplete/constants.js
web/gds-admin-ui/src/redux/autocomplete/index.js
web/gds-admin-ui/src/redux/autocomplete/reducers.js
web/gds-admin-ui/src/redux/autocomplete/saga.js
web/gds-admin-ui/src/redux/reducers.js
web/gds-admin-ui/src/redux/sagas.js
web/gds-admin-ui/src/redux/selectors/autocomplete.js
web/gds-admin-ui/src/redux/selectors/index.js
web/gds-admin-ui/src/services/autocomplete.js

feat: implement search bar in header

---

pkg/gds/secrets/token.go
pkg/gds/secrets/token_test.go

This adds a simple test for `CreateToken`.

sc-2347 add CreateToken test

---

pkg/gds/client/profile.go
pkg/gds/config/config.go
pkg/gds/config/config_test.go
pkg/gds/interceptor.go
pkg/gds/members.go
pkg/gds/mock.go
pkg/trtl/interceptor.go

Adds mTLS configuration for the TRISA members service.

GDS: mTLS configuration for members server

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/__tests__/review-note-form.spec.js
web/gds-admin-ui/src/__tests__/review-note.spec.js
web/gds-admin-ui/src/components/Oval.js
web/gds-admin-ui/src/components/OvalLoader.js
web/gds-admin-ui/src/index.js
web/gds-admin-ui/src/layouts/Vertical.js
web/gds-admin-ui/src/pages/app/dashboard/Statistics.js
web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/pages/app/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/dashboard/TasksChart.js
web/gds-admin-ui/src/pages/app/dashboard/index.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNote.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNoteForm.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/index.js
web/gds-admin-ui/src/pages/app/details/index.js
web/gds-admin-ui/src/pages/app/lists/index.js
web/gds-admin-ui/src/redux/dashboard/reducers.js
web/gds-admin-ui/src/redux/dashboard/saga.js
web/gds-admin-ui/src/redux/review-notes/reducers.js
web/gds-admin-ui/src/redux/review-notes/sagas.js
web/gds-admin-ui/src/setupTests.js
web/gds-admin-ui/src/utils/test-utils.js
web/gds-admin-ui/yarn.lock

Fixes SC-2501
I added in this task loader to let the user know that there an ongoing request
https://user-images.githubusercontent.com/54010836/146603493-ae97560b-e989-4b6a-9798-1b52f348f496.mov

feat: add placeholder for data loading

---

pkg/trtl/config/config.go
pkg/trtl/config/config_test.go
pkg/trtl/server.go
pkg/trtl/server_test.go

This adds the code for the trtl mTLS configuration that we developed together.

mTLS server configuration

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/components/BusinessCategory.js
web/gds-admin-ui/src/components/VaspCategory.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BasicDetailsDropdown.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BusinessInfosForm.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/redux/autocomplete/index.js
web/gds-admin-ui/src/redux/autocomplete/saga.js
web/gds-admin-ui/src/redux/sagas.js
web/gds-admin-ui/src/redux/vasp-details/actions.js
web/gds-admin-ui/src/redux/vasp-details/constants.js
web/gds-admin-ui/src/redux/vasp-details/reducers.js
web/gds-admin-ui/src/redux/vasp-details/sagas.js
web/gds-admin-ui/src/services/vasp.js
web/gds-admin-ui/src/utils/form-references.js
web/gds-admin-ui/yarn.lock

Fixes SC-2556
This PR adds an option to update the business informations
https://www.awesomescreenshot.com/video/6706970?key=cb210e86ce7dab66973ffc1bbe7886c0
Updated screen
- For a matters of UX I moved the submit and cancel button

feat: edit business infos

---

web/gds-admin-ui/README.md
web/gds-admin-ui/src/__tests__/basic-details.spec.js
web/gds-admin-ui/src/__tests__/certificate-details.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/config.js
web/gds-admin-ui/src/pages/app/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BasicDetailsDropdown.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/NationalIdentification.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/utils/index.js

fix unit tests sc-2923

---

web/gds-admin-ui/src/pages/app/dashboard/Tasks.js

Fix admin UI syntax errors

---

web/gds-admin-ui/src/__tests__/business-infos-form.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BasicDetailsDropdown.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BusinessInfosForm.js

Test business infos modal

---

go.mod
pkg/trtl/replica/doc.go
pkg/trtl/replica/sync.go

Adds a godoc that describes anti-entropy at a high level to assist with the development of the replica code.

Anti-Entropy godoc

---

web/gds-admin-ui/src/__tests__/basic-details.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/__tests__/national-identification.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/NationalIdentification.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js

Fixes SC-3452
This PR fixes the issue with country emoji flag in VASP basics details

fix:  UI should use IVMS101 country property to display flag

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/__tests__/contact.spec.js
web/gds-admin-ui/src/__tests__/delete-contact-prompt-modal.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/__tests__/trixo-questionnaire.js
web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/components/Field.js
web/gds-admin-ui/src/constants/index.js
web/gds-admin-ui/src/constants/trixo.js
web/gds-admin-ui/src/pages/app/details/TrixoQuestionnaire/index.js
web/gds-admin-ui/src/pages/app/details/contact/Contact.js
web/gds-admin-ui/src/pages/app/details/contact/DeleteContactModal.js
web/gds-admin-ui/src/pages/app/details/contact/DeleteContactPromptModal.js
web/gds-admin-ui/src/pages/app/details/contact/EditContactForm.js
web/gds-admin-ui/src/pages/app/details/contact/EditContactModal.js
web/gds-admin-ui/src/pages/app/details/contact/index.js
web/gds-admin-ui/src/redux/sagas.js
web/gds-admin-ui/src/redux/selectors/vasp-details.js
web/gds-admin-ui/src/redux/vasp-details/actions.js
web/gds-admin-ui/src/redux/vasp-details/constants.js
web/gds-admin-ui/src/redux/vasp-details/reducers.js
web/gds-admin-ui/src/redux/vasp-details/sagas.js
web/gds-admin-ui/src/services/vasp.js
web/gds-admin-ui/src/utils/form-references.js
web/gds-admin-ui/yarn.lock

SC-3356
This PR add features for updating, creating and deleting a contact
https://www.awesomescreenshot.com/video/7324691?key=d59d19a2945d21b6f3ba08f857f21411

sc-3356 Support adding, updating, and deleting contacts

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Ivms101RecordForm.js

remove the country of issue field or set it to unselected from the UI

---

pkg/gds/store/trtl/iterator.go
pkg/gds/store/trtl/iterator_test.go

This adds tests for the two trtl iterator types and fixes some edge cases in the iterators to protect us from panics.

sc-3394 trtl iterator tests

---

web/gds-admin-ui/src/components/Auth/SignWithGoogle.js
web/gds-admin-ui/src/contexts/auth/auth-provider.js
web/gds-admin-ui/src/helpers/api/apiCore.js
web/gds-admin-ui/src/pages/account/Login.js
web/gds-admin-ui/src/pages/app/details/index.js

fix: Error message when authentication fails

---

pkg/gds/store/leveldb/leveldb.go
pkg/gds/store/trtl/index.go
pkg/gds/store/trtl/index_test.go
pkg/gds/store/trtl/mock.go
pkg/gds/store/trtl/trtl.go
pkg/gds/store/trtl/trtl_test.go
pkg/trtl/namespaces.go
pkg/trtl/trtl.go
pkg/trtl/trtl_test.go

This PR adds the ported indices to the trtl store in preparation for the GDS 1.3 release.

Add indices to Trtl Store

---

containers/docker-compose.yaml
containers/monitor/.gitignore
containers/monitor/grafana/dashboards/trtl.json
containers/monitor/prometheus.yml

Adds Prometheus and Grafana to Docker Compose for local developement.

Add Prometheus and Grafana to Docker Compose

---

cmd/gdsutil/main.go
cmd/trtl/main.go
pkg/gds/certs.go

Opened at the request of @bbengfort

Hotfix Certificate Issuance Panic in MainNet

---

cmd/trtlsim/main.go
containers/build.sh
containers/gds/Dockerfile

This PR implements some container maintenance.

Add trtl and remove sectigo from GDS pod

---

web/gds-user-ui/src/components/section/LegalPerson.stories.tsx
web/gds-user-ui/src/components/section/LegalPerson.tsx
web/gds-user-ui/src/components/section/LegalPersonForm.stories.tsx
web/gds-user-ui/src/components/section/LegalPersonForm.tsx
web/gds-user-ui/src/layouts/FormLayout.tsx

sc-3969 legal adresses base component

---

pkg/bff/server.go
pkg/bff/status.go

Implements a Gin HTTP API server for the BFF using the config from #379. 
Blocked by #379

GDS BFF API Server

---

cmd/bff/main.go

Implements a urfave v2 CLI binary for running the BFF server.

Create BFF Binary

---

.github/workflows/containers.yaml
containers/bff/Dockerfile
containers/build.sh
containers/docker-compose.yaml

Implements the GDS BFF Dockerfile, adds the BFF to the docker-compose container and to the GitHub actions for build and push when the version is incremented. 
Files to review:
- containers/bff/Dockerfile
- containers/build.sh
- containers/docker-compose.yaml
- .workflows/github/containers.yaml
Blocked by #382

GDS BFF Dockerfile

---

web/gds-user-ui/src/components/DetailsCard/DetailsCard.stories.tsx
web/gds-user-ui/src/components/DetailsCard/index.tsx
web/gds-user-ui/src/components/Icon/EllipseIcon.tsx
web/gds-user-ui/src/components/NeedsAttention/NeedsAttention.stories.tsx
web/gds-user-ui/src/components/NeedsAttention/index.tsx
web/gds-user-ui/src/components/NetworkAnnouncements/NetworkAnnouncements.stories.tsx
web/gds-user-ui/src/components/NetworkAnnouncements/index.tsx
web/gds-user-ui/src/components/NetworkStatus/NetworkStatus.stories.tsx
web/gds-user-ui/src/components/NetworkStatus/index.tsx
web/gds-user-ui/src/components/StatCard/StatCard.stories.tsx
web/gds-user-ui/src/components/StatCard/index.tsx
web/gds-user-ui/src/components/StatusCard/index.tsx
web/gds-user-ui/src/components/StatusCard/statuscard.stories.tsx
web/gds-user-ui/src/components/section/CreateAccount.stories.tsx
web/gds-user-ui/src/components/section/Login.stories.tsx

The following components are included in this PR:
- NeedsAttention Component
- NetworkStatus Component
- StatCard Component
- StatusCard Component
- DetailsCard Component

Sc-3594: Dashboard overview components

---

containers/docker-compose.yaml
pkg/bff/gds.go
pkg/bff/gds_test.go
pkg/bff/server_test.go
pkg/bff/testdata/contacts.json
pkg/bff/testdata/entity.json
pkg/bff/testdata/mainnet/register_reply.json
pkg/bff/testdata/testnet/register_reply.json
pkg/bff/testdata/trixo.json

This PR implements tests for the Register BFF endpoint.
TODO: add multiple directory services and BFF to docker compose so that @masskoder and @elysee15 can start developing against it.

BFF Register Tests

---

pkg/gds/admin_test.go
pkg/gds/certs_test.go
pkg/gds/gds_test.go
pkg/gds/service_test.go

This cleans up the ResetFixtures functions which were no longer necessary in favor of a single function.

sc-3985 ResetFixtures cleanup

---

web/gds-admin-ui/src/components/ResendEmail.js

sc-3670 POST to resend results in 405 Not Allowed

---

web/gds-user-ui/public/index.html
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/NameIdentifier/index.tsx
web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx
web/gds-user-ui/src/components/ui/InputFormControl/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/defaultValues.ts
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts

sc-4846 change the website name

---

web/gds-user-ui/src/components/CertificateReview/index.tsx
web/gds-user-ui/src/components/CountryOfRegistration/index.tsx
web/gds-user-ui/src/components/ReviewSubmit/ConfirmationModal.tsx
web/gds-user-ui/src/components/ReviewSubmit/ModalAlert.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts

Added required validation to country of registration field  & display alert modal for understood button

sc-4867 refactor: Implement alert message behind understood button

---

web/gds-user-ui/src/application/config/index.ts
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/index.tsx
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/components/NameIdentifier/index.tsx
web/gds-user-ui/src/components/ReviewSubmit/ConfirmationModal.tsx
web/gds-user-ui/src/components/ReviewSubmit/ModalAlert.tsx
web/gds-user-ui/src/constants/national-identification.ts
web/gds-user-ui/src/hooks/useAnalytics.ts
web/gds-user-ui/src/hooks/useCertificateStepper.ts
web/gds-user-ui/src/layouts/SimpleDashboardLayout.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/modules/verify/index.tsx
web/gds-user-ui/src/utils/registration-authority.json
web/gds-user-ui/src/utils/utils.ts

After the Smoke test #5, we noticed some issues that need to be reviewed. 
- fixed the copy of the success message on Verify contact page
- disable for now legal person value on national identification type
- disable the country of issue for the Legal person options
- refactoring the registration authorities option list
after a pull or fetch ,  just checkout to branch `sc-4974`

Sc-4974 : refactoring registration authorities option List

---

web/gds-user-ui/src/components/NameIdentifier/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts

Briefly add notes if applicable and include the story ID 

set name identifier type to required if the identifier name is filled out

---

web/gds-user-ui/cypress.json
web/gds-user-ui/cypress/plugins/index.js
web/gds-user-ui/cypress/support/commands.js
web/gds-user-ui/cypress/support/index.js
web/gds-user-ui/package.json
web/gds-user-ui/tsconfig.json
web/gds-user-ui/yarn.lock

Briefly add notes if applicable and include the story ID 

sc-3666 GDS UI refactor: set up cypress for integration testing

---

web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/components/SectionStatus/SectionStatus.tsx
web/gds-user-ui/src/types/type.d.ts
web/gds-user-ui/src/utils/country.ts
web/gds-user-ui/src/utils/utils.ts
web/gds-user-ui/tsconfig.json

Briefly add notes if applicable and include the story ID 

sc-4926 Search result: signature should be under its identity signatures like a header

---

web/gds-user-ui/src/components/Section/AboutUs.tsx
web/gds-user-ui/src/components/Section/JoinUs.tsx
web/gds-user-ui/src/components/Section/VaspVerification.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx

sc-5090: Fix Typos & Copy on GDS landing page & reg form
Just open the landing page to see the copy update as described in the story sc-5090

sc-5090 : Fix typo & copy on GDS landing page & reg form

---

web/gds-user-ui/package.json
web/gds-user-ui/src/App.test.tsx
web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/NameIdentifier/index.tsx
web/gds-user-ui/src/components/ui/InputFormControl/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.spec.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/setupTests.ts
web/gds-user-ui/src/utils/test-utils.tsx
web/gds-user-ui/yarn.lock

Wrote units tests for certificate registration form steps
My tests are included inside the `registration` component folder

sc-3908 GDS USER ADMIN UI : certificate registration unit tests

---

web/gds-user-ui/src/components/Head/LandingHead.tsx
web/gds-user-ui/src/components/Section/VaspVerification.tsx
web/gds-user-ui/src/utils/theme.ts

sc-5296 Fix Formatting on "Getting Started" page
We needed to have a unified style for this page: typographic, margin and layout styles: 
Click on `Join Today` to see the screen

sc-5296 Fix Formatting on "Getting Started" page

---

web/gds-user-ui/src/components/Menu/Landing/MenuItem.tsx
web/gds-user-ui/src/components/Section/VaspVerification.tsx

Sc-5280: improve the landing header menu item style

Sc-5280: improve the landing header menu item style

---

web/gds-user-ui/src/layouts/SimpleDashboardLayout.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx

Sc-4947: Fix form background color to extend to footer

Sc-4947: Fix form background color to extend to footer

---

web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Menu/Landing/MenuItem.tsx
web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/components/Section/VaspVerification.tsx

Sc-5266: Remove search term in the lookup result
run docker and try to make a search to notice this changes

Sc-5266: Remove search term in the lookup result

---

web/gds-user-ui/src/application/routes/index.tsx
web/gds-user-ui/src/components/Section/PasswordReset.stories.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/components/ui/SuccessMessage.tsx
web/gds-user-ui/src/hooks/useCustomAuth0.ts
web/gds-user-ui/src/modules/auth/reset/index.tsx

sc-5196: implement a reset password feature
Go to the `account/reset` route and fill out your email. Auth0 will send you an email to change your password.

sc-5196: implement reset password feature

---

.github/workflows/tests.yaml
web/gds-user-ui/package.json
web/gds-user-ui/src/components/AddressForm/index.tsx
web/gds-user-ui/src/components/Addresses/index.tsx
web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/CountryOfRegistration/index.tsx
web/gds-user-ui/src/components/LegalPerson/index.tsx
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx

GDS User UI : set up Github action for User UI
I have added a github action's job in the `.github` folder that will run unit tests on gds user ui

sc-5250 GDS User UI : set up Github action for User UI

---

web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/Head/LandingHead.tsx
web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Section/AboutUs.tsx
web/gds-user-ui/src/components/Section/JoinUs.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/components/ui/HomeButton.tsx

Sc-5345:  Copy updates && landing page improvement

Sc-5345:  Copy updates && landing page improvement

---

web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx

sc-5264: disable login menu for gds v1.4.1

sc-5264: disable login menu for gds v1.4.1

---

web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/Head/LandingHead.tsx
web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Section/AboutUs.tsx
web/gds-user-ui/src/components/Section/JoinUs.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/components/ui/HomeButton.tsx
web/gds-user-ui/src/modules/home/index.tsx

Sc-5260: Clean up search result card 
- []   Check this box if a reviewer can merge this pull request after approval (leave it unchecked if you want to do it yourself)

Sc-5260: Clean up search result card 

---

web/gds-user-ui/src/App.tsx

sc-5105: Implement sentry profiler

sc-5105: Implement sentry profiler

---

web/gds-user-ui/src/components/Section/SearchDirectory.tsx

sc-5373 GDS UI User: Datatable should be responsive

sc-5373 GDS UI User: Datatable should be responsive

---

web/gds-user-ui/src/components/Section/CreateAccount.spec.tsx
web/gds-user-ui/src/components/Section/CreateAccount.tsx
web/gds-user-ui/src/components/ui/InputFormControl/index.tsx
web/gds-user-ui/src/modules/auth/register/register.validation.ts

sc-5354 GDS User UI: Look at the form validation  & implement the unit test of sign up feature
Verify and improve form validation for account creation, and implement unit tests

sc-5354 implement the unit test of sign up feature

---

web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx

sc-5476 fix padding on review page

sc-5476 fix padding on review page

---

web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/Head/LandingHead.tsx
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/components/Section/VaspVerification.tsx
web/gds-user-ui/src/utils/utils.ts

Sc-5441: Added a filter to display authorities options based on selected countries

Sc-5441: Added a filter to display authorities options based on selected countries

---

web/gds-user-ui/.eslintrc.json
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/utils/utils.ts

sc-5443 GDS User UI: We should include more information such as the comments and website of the authority

sc-5443 include more informations such as the comments and website of the authority

---

web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/components/Section/JoinUs.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/defaultValues.ts
web/gds-user-ui/src/types/type.d.ts
web/gds-user-ui/src/utils/address-utils.tsx
web/gds-user-ui/src/utils/utils.ts

…ection
sc-5566: Improve GDS User UI for v.1.4.1

sc-5566: Improve GDS User UI for v.1.4.1

---

web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts

sc-5566 : typos fixes 

---

web/gds-user-ui/.linguirc
web/gds-user-ui/package.json
web/gds-user-ui/src/App.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementation.spec.tsx
web/gds-user-ui/src/components/CertificateReview/__snapshots__/TrisaImplementation.spec.tsx.snap
web/gds-user-ui/src/components/Section/AboutUs.tsx
web/gds-user-ui/src/locales/de/messages.js
web/gds-user-ui/src/locales/de/messages.po
web/gds-user-ui/src/locales/en/messages.js
web/gds-user-ui/src/locales/en/messages.po
web/gds-user-ui/src/locales/fr/messages.js
web/gds-user-ui/src/locales/fr/messages.po
web/gds-user-ui/src/locales/ja/messages.js
web/gds-user-ui/src/locales/ja/messages.po
web/gds-user-ui/src/locales/zh/messages.js
web/gds-user-ui/src/locales/zh/messages.po
web/gds-user-ui/src/types/type.d.ts
web/gds-user-ui/src/utils/i18nLoaderHelper.ts
web/gds-user-ui/yarn.lock

sc-3491 setup Lingui for internalization
Change the `DEFAULT_LOCALE` in the `i18nLoaderHelper` to `fr`, I have added a translation of `About TRISA` then you can the change in the UI

sc-3491 setup Lingui for internalization

---

pkg/bff/members.go
pkg/bff/members_test.go
pkg/bff/server.go

Adds a mock overview endpoint to unblock @masskoder and @elysee15 developing the front end until Patrick can get to SC-4310.
Fixes SC-5824

GDS BFF: Overview Endpoint Mock

---

web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx

fix(sentry-bug): solve str toUpperCase is not function error
sc-5731: fix(sentry-bug) solve str toUpperCase is not function error

sc-5731: fix(sentry-bug) solve str toUpperCase is not function error

---

web/gds-user-ui/src/components/PasswordStrength/index.tsx

fix: remove unnecessary escape character
fix: remove unnecessary escape character

fix: remove unnecessary escape character

---

web/gds-user-ui/package.json
web/gds-user-ui/src/components/CollaboratorsSection/index.tsx
web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Menu/Landing/MenuItem.tsx

sc-3639 GDS UI refresh: Collaborators - Action options (Component)
I modified the `Organizations Collaborators` options to
It can be tested in `storybook` by searching the `CollaboratorsSection` story

sc-3639 GDS UI refresh: Collaborators - Action options (Component)

---

web/gds-user-ui/.storybook/preview.js
web/gds-user-ui/src/components/Section/IntegrateAndComply.tsx
web/gds-user-ui/src/components/Section/Line.tsx
web/gds-user-ui/src/components/Section/__tests__/IntegrateAndComply.spec.tsx
web/gds-user-ui/src/components/Section/__tests__/Line.spec.tsx
web/gds-user-ui/src/components/Section/__tests__/VaspVerification.spec.tsx
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/IntegrateAndComply.spec.tsx.snap
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/VaspVerification.spec.tsx.snap

sc-6068 GDS User UI : implement comply page

sc-6068 GDS User UI : implement comply page

---

web/gds-user-ui/package.json
web/gds-user-ui/src/components/Header/LandingHeader.spec.tsx
web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Menu/Landing/MenuItem.spec.tsx
web/gds-user-ui/src/components/Section/CreateAccount.spec.tsx
web/gds-user-ui/src/constants/lang-key.ts
web/gds-user-ui/src/constants/trisa-base-url.ts
web/gds-user-ui/src/contexts/LanguageContext.tsx
web/gds-user-ui/src/modules/auth/login/login.spec.tsx
web/gds-user-ui/src/utils/test-utils.tsx

sc-1557 Link based language selection
Change the app language and click on `documentation` menu you'll see that the language change according to the changed language

sc-1557 Link based language selection

---

web/gds-admin-ui/src/__tests__/Footer.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/assets/scss/app.scss
web/gds-admin-ui/src/config.js
web/gds-admin-ui/src/layouts/Footer.js
web/gds-admin-ui/src/services/version.js
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/VaspVerification.spec.tsx.snap

Sc 4862  Add Version Information to Admin UI
I have added according to the story the `API version`, `Git version` and `App version` in the footer section. You'll be able to the git version and app version in prod env

Sc 4862  Add Version Information to Admin UI

---

web/gds-user-ui/src/components/ContentLoader/Overview.tsx
web/gds-user-ui/src/modules/dashboard/overview/index.tsx

sc-6140: add overview content loader
After the login process, you can see the overview content loader.

sc-6140: add overview content loader

---

web/gds-user-ui/src/components/Footer/LandingFooter.tsx
web/gds-user-ui/src/components/Navbar/Landing/Nav.tsx
web/gds-user-ui/src/components/Section/Login.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/components/Section/PasswordResetFail.tsx
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/VaspVerification.spec.tsx.snap
web/gds-user-ui/src/layouts/LandingLayout.tsx
web/gds-user-ui/src/modules/home/index.tsx

sc-6222 GDS User UI: fix footer

sc-6222 GDS User UI: fix footer

---

pkg/bff/api/v1/client_test.go
pkg/bff/api/v1/errors_test.go

SC-6346: Fixes an incorrect import in the tests and improves the BFF API definitions test coverage.

Fix wrong test import and increase BFF client coverage

---

pkg/bff/admin.go
pkg/bff/admin_test.go
pkg/bff/api/v1/api.go
pkg/bff/api/v1/client.go
pkg/bff/api/v1/client_test.go
pkg/bff/server.go

This adds stubs for a list certificates endpoint on the bff. When we get the admin API endpoint up and running and have the ability to authenticate with it from the bff, then we can fully implement this endpoint.
The certificate reply structure should make sense.

bff list certificates stub

---

web/gds-user-ui/src/components/Metrics/index.tsx
web/gds-user-ui/src/components/StatusCard/index.tsx

sc-6636: fix .toUppercase is not function issue on overview page and added sentry boundary 

sc-6636: fix .toUppercase is not function issue on overview page

---

web/gds-user-ui/src/components/LanguagesDropdown/index.tsx
web/gds-user-ui/src/components/Section/IntegrateAndComply.tsx
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/VaspVerification.spec.tsx.snap

sc-6639 GDS UI : Comply page Fixes

sc-6639 GDS UI : Comply page Fixes

---

web/gds-admin-ui/src/pages/app/dashboard/Status.js
web/gds-admin-ui/src/utils/__test__/roundUpToTwo.spec.js
web/gds-admin-ui/src/utils/roundUptoTwo.js
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/VaspVerification.spec.tsx.snap

SC-6462 Floating point error in admin.trisatest.net/dashboard
I have added improvements on how to calculate status ratio percentage to be sure that it round them correctly.
For instance 
`7.00001` will be `7`
`7.56666` will be `7.57`

SC-6462 Floating point error in admin.trisatest.net/dashboard

---

web/gds-user-ui/.gitignore
web/gds-user-ui/src/components/AddressForm/AddressForm.spec.tsx
web/gds-user-ui/src/components/AddressForm/index.tsx
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/components/ui/InputFormControl/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts
web/gds-user-ui/src/modules/dashboard/certificate/registration.spec.tsx
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap

sc-6702 Update Legal Person section on Certificate Registration Form with new address fields

sc-6702 Update Legal Person section on Certificate Registration Form

---

web/gds-user-ui/src/application/config/sentry.ts

sc-5727 Add releases to Sentry frontend

sc-5727 Add releases to Sentry frontend

---

web/gds-user-ui/.storybook/preview.js
web/gds-user-ui/src/application/routes/routes.ts
web/gds-user-ui/src/components/CertificateManagement/CertificateManagement.stories.tsx
web/gds-user-ui/src/components/CertificateManagement/SealingCertificateTableRows.tsx
web/gds-user-ui/src/components/CertificateManagement/StatisticCard.tsx
web/gds-user-ui/src/components/CertificateManagement/X509IdentityCertificateInventory.tsx
web/gds-user-ui/src/components/CertificateManagement/X509TableRows.tsx
web/gds-user-ui/src/components/CertificateManagement/index.tsx
web/gds-user-ui/src/components/NeedsAttention/NeedsAttention.stories.tsx
web/gds-user-ui/src/components/NeedsAttention/index.tsx
web/gds-user-ui/src/components/OptionsMenu.tsx
web/gds-user-ui/src/components/TableRow/RowItem.tsx
web/gds-user-ui/src/components/TableRow/index.tsx
web/gds-user-ui/src/components/TechnicalResources/index.tsx
web/gds-user-ui/src/modules/dashboard/overview/index.tsx

sc-6736 GDS UI : Certificate management Page View

sc-6736 GDS UI : Certificate management Page View

---

web/gds-user-ui/src/components/CertificateRegistration/index.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx

sc-5458 GDS User UI: make certificate review & submit responsive

sc-5458 GDS User UI: make certificate review & submit responsive

---

web/gds-user-ui/src/components/BasicDetail/index.tsx

sc-7085 GDS UI User: improve the input form length
This PR fixes the issue on Basic Details max length that was not fit the available width

sc-7085 GDS UI User: improve the input form length

---

web/gds-user-ui/src/App.tsx
web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/CertificateRegistration/index.tsx
web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/Head/LandingHead.tsx
web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/Section/Login.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx
web/gds-user-ui/src/components/ui/HomeButton.tsx
web/gds-user-ui/src/index.tsx
web/gds-user-ui/src/layouts/FormLayout.tsx
web/gds-user-ui/src/layouts/LandingLayout.tsx
web/gds-user-ui/src/layouts/SimpleDashboardLayout.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/theme/index.ts

sc-7087 GDS User UI : implement the dark mode

sc-7087 GDS User UI : implement the dark mode

---

web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/ChakraRouterLink.tsx
web/gds-user-ui/src/components/Section/CreateAccount.tsx
web/gds-user-ui/src/components/Section/Login.tsx
web/gds-user-ui/src/components/Section/PasswordReset.tsx
web/gds-user-ui/src/layouts/LandingLayout.tsx
web/gds-user-ui/src/layouts/SimpleDashboardLayout.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/modules/dashboard/overview/index.tsx
web/gds-user-ui/src/theme/components/Input.ts

sc-7286 GDS User UI: fix app layout
I fixed the width of the whole app layout to avoid stretching on very large screens

sc-7286 GDS User UI: fix app layout

---

web/gds-user-ui/src/components/CertificateRegistration/CertificateRegistrationTable.tsx
web/gds-user-ui/src/components/CertificateRegistration/index.tsx
web/gds-user-ui/src/components/Tables/CertificateRegistrationRow.tsx
web/gds-user-ui/src/components/Tables/MembersRow.tsx

sc-7337 GDS User UI: refact certificate registration component
refact certificate registration component

sc-7337 GDS User UI: refact certificate registration component

---

web/gds-user-ui/src/components/Header/LandingHeader.tsx

sc-7565 GDS User UI : remove the dark mode switch button
for the release, we don't need this feature for now. we will display it for the next release.

sc-7565 GDS User UI : remove the dark mode switch button

---

web/gds-user-ui/src/application/routes/PrivateOutlet.tsx
web/gds-user-ui/src/components/CertificateSection/index.tsx
web/gds-user-ui/src/components/Section/GettingStarted.tsx
web/gds-user-ui/src/components/Section/IntegrateAndComply.tsx
web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/components/Section/VaspVerification.tsx
web/gds-user-ui/src/components/Sidebar/NavItem.tsx
web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx

sc-7548 GDS USER UI : fix broken link
- in comply page, we have to fix all broken link
- in sidebar we should add slack and support link

sc-7548 GDS USER UI : fix broken link

---

web/gds-user-ui/src/components/Section/SearchDirectory.tsx

sc-7561 GDS User UI : help cursor doesnt work in search directory component

sc-7561 GDS User UI : help cursor doesnt work in search directory component

---

web/gds-user-ui/src/components/Section/SearchDirectory.tsx

sc-7564: fix the mainnet response data issue
sc-7564: fix the mainnet response data issue

sc-7564: fix the mainnet response data issue

---

web/gds-user-ui/src/components/OrganizationProfile/OrganizationalDetail.tsx

Sc-7569 : fix white text content in the profile component 
Sc-7569 : fix white text content in the profile component

Sc-7569 : fix white text content in profile component 

---

web/gds-user-ui/src/components/OrganizationProfile/OrganizationalDetail.tsx

Sc-7547 : make Trisa organization profile cards responsive

Sc-7547 : make Trisa organization profile cards responsive

---

cmd/reissuer/main.go

This PR adds automated email notifications to the reissuer CMD.

Automatically send Whisper link in Reissuer command

---

.github/workflows/staging.yaml

staging.yaml under workflows

---

web/gds-user-ui/src/components/Sidebar/MobileNav.tsx
web/gds-user-ui/src/components/ui/Logo.tsx

sc-8052 GDS User UI : replace Logo with trisa logo in mobile device

sc-8052 GDS User UI : replace Logo with trisa logo in mobile device

---

web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts

At this point after login, we're redirected to /auth/callback but we're getting an error:
```
Objects are not valid as a React child
```
For the first stage, we just added a console log to figure out where the error really came from.

sc-8210:  Objects are not valid as a React child

---

web/gds-user-ui/src/components/ui/AlertMessage.tsx
web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts
web/gds-user-ui/src/utils/utils.ts

sc-8210: hotfix - refactoring callback component 
sc-8210: hotfix - refactoring callback component

sc-8210: hotfix - refactoring callback component 

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Geographic.js
web/gds-user-ui/src/modules/auth/login/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/modules/dashboard/registration/utils.ts
web/gds-user-ui/src/utils/axios.ts
web/gds-user-ui/src/utils/utils.ts

Sc:8265 :  certificate legal person step bug fix
go through the application

Sc-8265 :  certificate legal person step bug fix

---

web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/Contacts/index.tsx
web/gds-user-ui/src/components/LegalPerson/index.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/components/SectionStatus/NotSavedSectionSection.tsx
web/gds-user-ui/src/components/SectionStatus/SavedSectionStatus.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx
web/gds-user-ui/src/components/TrisaImplementation/index.tsx
web/gds-user-ui/src/components/TrixoQuestionnaire/index.tsx

refactor(user-ui): improve the contrast of the shadow gradient
refactor(user-ui): improve the contrast of the shadow gradient

refactor(user-ui): improve the contrast of the shadow gradient

---

web/gds-user-ui/src/components/CertificateManagement/StatisticCard.stories.tsx
web/gds-user-ui/src/components/CertificateManagement/StatisticCard.tsx
web/gds-user-ui/src/components/Sidebar/NavItem.tsx
web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx

sc-7457 GDS User UI : refactoring statistics card component to be responsive

sc-7457 GDS User UI : refactoring statistics card component to be responsive

---

web/gds-user-ui/src/components/Sidebar/ArrowIcon.tsx
web/gds-user-ui/src/components/Sidebar/NavItem.tsx
web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx
web/gds-user-ui/src/utils/menu.ts

fix sidebar dropdown

---

web/gds-user-ui/src/components/OrganizationProfile/OrganizationalDetail.tsx
web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/dashboard/overview/index.tsx
web/gds-user-ui/src/utils/utils.ts

Sc-8305: redirect user to login page if authentication error
Sc-8305: redirect user to login page if authentication error

Sc-8305: redirect user to login page if authentication error

---

web/gds-user-ui/src/components/CertificateReview/index.tsx
web/gds-user-ui/src/components/Modal/ConfirmationResetFormModal.tsx
web/gds-user-ui/src/components/OrganizationProfile/OrganizationalDetail.tsx
web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/modules/dashboard/overview/index.tsx
web/gds-user-ui/src/utils/utils.ts

Sc-8323: reset form value 
Sc-8323: reset form value

sc-8323: reset form value 

---

web/gds-user-ui/src/components/Regulations/Regulations.spec.tsx
web/gds-user-ui/src/components/Regulations/index.tsx

sc-8321 GDS User Ui : fix Applicable Regulations fields name issue

sc-8321 GDS User Ui : fix Applicable Regulations fields name issue

---

web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/locales/de/messages.po
web/gds-user-ui/src/locales/en-dh/messages.po
web/gds-user-ui/src/locales/en/messages.po
web/gds-user-ui/src/locales/fr/messages.po
web/gds-user-ui/src/locales/ja/messages.po
web/gds-user-ui/src/locales/zh/messages.po

sc-8314 Grammar and punctuation issues on Submit Registration page

sc-8314 Grammar and punctuation issues on Submit Registration page

---

web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts
web/gds-user-ui/src/utils/auth0.helper.ts

sc-8259: generate a new token if refresh token flag is set
sc-8259: generate a new token if refresh token flag is set

sc-8259: generate a new token if refresh token flag is set

---

pkg/gds/emails/bindata.go
pkg/gds/emails/client.go
pkg/gds/emails/client_test.go
pkg/gds/emails/emails.go
pkg/gds/emails/emails_test.go
pkg/gds/emails/subjects.go
pkg/gds/emails/templates/reissuance_admin_notification.html
pkg/gds/emails/templates/reissuance_admin_notification.txt

added reissuance admin notification email [sc-6625](https://app.shortcut.com/rotational/story/6625/implement-trisa-admin-email-notification)
Review against Expires Admin Notification Email

added reissuance admin notification email sc-6625

---

web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.spec.tsx
web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.stories.tsx
web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.spec.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.stories.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReview.tsx
web/gds-user-ui/src/components/CertificateReview/ContactsReviewDataTable.tsx
web/gds-user-ui/src/components/CertificateReview/ReviewsSummary.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementation.spec.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.spec.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.stories.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReview.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.spec.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.stories.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReview.tsx
web/gds-user-ui/src/components/CertificateReview/__snapshots__/ContactsReview.spec.tsx.snap
web/gds-user-ui/src/components/NeedsAttention/AttentionAlert.tsx
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/components/TestnetProgress/CertificateStepContainer.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateSteps.tsx
web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx
web/gds-user-ui/src/hooks/useCertificateStepper.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/modules/dashboard/registration/utils.ts
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap
web/gds-user-ui/src/utils/axios.ts
web/gds-user-ui/src/utils/utils.ts

Sc-8448 : fix incorporate date format & minor fixes 
Sc-8448 : fix incorporate date format & minor fixes

Sc-8448 : fix incorporate date format & minor fixes 

---

web/gds-user-ui/src/components/CertificateReview/TrixoReviewDataTable.tsx
web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx
web/gds-user-ui/src/constants/trixo.ts

sc-8669: minor fixes on trixo form
sc-8669: minor fixes on trixo form

sc-8669: minor fixes on trixo form

---

web/gds-user-ui/src/components/CertificateReview/LegalPersonReviewDataTable.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx

sc-8415 fix broken link on review page link
The links in the text, "return to the Review Page" send the user to the Overview rather than the review page.

sc-8415 fix broken link on review page link

---

web/gds-user-ui/src/application/store/selectors/stepper.ts
web/gds-user-ui/src/components/CertificateReview/TrixoReviewDataTable.tsx
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx

… button
sc-8533 GDS User UI : add review page button before the clear & reset button

sc-8533 GDS User UI : add review page button before the clear & reset button

---

web/gds-user-ui/src/components/CertificateReview/TrixoReviewDataTable.tsx

sc-8444 Review page: Fix headers of different length

sc-8444 Review page: Fix headers of different length

---

pkg/bff/gds.go
pkg/bff/members.go
pkg/bff/server_test.go
web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/validationSchema.ts
web/gds-user-ui/src/utils/formate-date.ts

sc-8408 Add min/max to date of incorporation field
https://www.awesomescreenshot.com/video/10713485?key=7eedbcbb545bf881429a9f60ea428171

sc-8408 Add min/max to date of incorporation field

---

web/gds-user-ui/package.json
web/gds-user-ui/src/application/routes/LandingOutlet.tsx
web/gds-user-ui/src/components/CertificateReview/BasicDetailsReview.tsx
web/gds-user-ui/src/components/CertificateReview/BasicDetailsReviewDataTable.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReviewDataTable.tsx
web/gds-user-ui/src/components/CertificateReview/__snapshots__/BasicDetailsReview.spec.tsx.snap
web/gds-user-ui/src/components/CertificateReview/__snapshots__/TrixoReview.spec.tsx.snap
web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx
web/gds-user-ui/yarn.lock

…r is logged
- add missing organization name fields in basic detail review 
- allow users to navigate to the landing page routes even if they are logged in
log in and go to the dashboard overview. after that try to manually open `/getting-started`

sc-8702: add missing organization name fields in basic detail review & minor improvements

---

pkg/bff/gds.go
pkg/bff/members.go
pkg/bff/server_test.go
pkg/version.go
web/gds-user-ui/src/components/CertificateReview/LegalPersonReviewDataTable.tsx

sc-8440 Review page: Header bar and text overflows when page is resized

sc-8440 Review page: Header bar and text overflows when page is resized

---

web/gds-user-ui/src/theme/index.ts

GDS User UI : Remove blue border from css custom-styled button
[sc-7976](https://app.shortcut.com/rotational/story/7976/gds-user-ui-remove-blue-border-from-css-custom-styled-button)

GDS User UI : Remove blue border from css custom-styled button

---

pkg/gds/models/v1/contacts.go
pkg/gds/models/v1/contacts_test.go

This adds some test coverage for the GetSentEmailCount helper method in the models package. This method is important for preventing spamming the contacts with duplicate emails so we need to be confident that the logic is correct.
SC-8902
Unit tests should pass

GetSentEmailCount tests

---

web/gds-user-ui/src/components/CertificateReview/ReviewsSummary.tsx
web/gds-user-ui/src/components/FileUpload/index.tsx

sc-8264 Import file button
https://app.shortcut.com/rotational/story/8264/import-file-button

sc-8264 update import file button

---

web/gds-admin-ui/src/__mocks__/other-jurisdictions.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/__tests__/national-identification.spec.js
web/gds-admin-ui/src/components/Modal/index.js
web/gds-admin-ui/src/helpers/api/apiCore.js
web/gds-admin-ui/src/pages/app/details/contact/EditContactForm.js
web/gds-admin-ui/src/redux/selectors/vasp-details.js
web/gds-admin-ui/src/redux/vasp-details/actions.js
web/gds-admin-ui/src/redux/vasp-details/constants.js
web/gds-admin-ui/src/redux/vasp-details/reducers.js
web/gds-admin-ui/src/redux/vasp-details/sagas.js

sc-7629 Admin UI Does Not Indicate Error when Contact Editing Has Failed

sc-7629 Admin UI Does Not Indicate Error when Contact Editing Has Failed

---

web/gds-user-ui/src/components/CertificateReview/__snapshots__/TrixoReview.spec.tsx.snap
web/gds-user-ui/src/components/TrisaImplementationForm/index.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/trisaImplementationValidationSchema.ts

sc-9263 Fix Error Msg Typos on TRISA Implementation Page
https://app.shortcut.com/rotational/story/9263/fix-error-msg-typos-on-trisa-implementation-page

sc-9263 Fix Error Msg Typos on TRISA Implementation Page

---

web/gds-user-ui/package.json
web/gds-user-ui/src/modules/dashboard/certificate/lib/basicDetailsValidationSchema.ts
web/gds-user-ui/yarn.lock

sc-9037 GDS User UI : update Date of incorporation / establishment error message
https://app.shortcut.com/rotational/story/9037/gds-user-ui-disallow-users-to-select-a-future-date-on-date-of-incorporation-establishment

sc-9037 GDS User UI : update Date of incorporation / establishment error message

---

web/gds-user-ui/src/components/CertificateReview/LegalPersonReviewDataTable.tsx
web/gds-user-ui/src/components/MemberDetails/index.tsx
web/gds-user-ui/src/components/ReviewSubmit/MainNetWarningBox.tsx
web/gds-user-ui/src/components/ReviewSubmit/TestNetWarningBox.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/components/WarningBox.tsx
web/gds-user-ui/src/hooks/useCertificateStepper.tsx

sc-8964 update warning message on submit review page
https://app.shortcut.com/rotational/story/8964/turn-step-4-trisa-implementation-into-an-optional-step-until-submission

sc-8964 update warning message on submit review page

---

web/gds-user-ui/src/components/Header/LandingHeader.tsx
web/gds-user-ui/src/layouts/AuthLayout.tsx

sc-9182 GDS USER UI : fix mobile nav menu on small screen

sc-9182 GDS USER UI : fix mobile nav menu on small screen

---

web/gds-user-ui/src/components/OrganizationProfile/OrganizationalDetail.tsx
web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/basicDetailsValidationSchema.ts
web/gds-user-ui/src/utils/utils.ts

fix: translation warning makes unit tests fail

fix: translation warning makes unit tests fail

---

web/gds-admin-ui/src/components/TimeAgo.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNote.js

sc-7785 GDS Admin UI: Reviewer Notes timestamp bug

sc-7785 GDS Admin UI: Reviewer Notes timestamp bug

---

web/gds-user-ui/src/components/BasicDetail/index.tsx

add console log to understand production behavior

---

web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts
web/gds-user-ui/src/modules/dashboard/registration/utils.ts

Update the status code for the PUT method

Update the status code for the PUT method

---

pkg/trtl/trtl.go

This PR changes a couple of errors that we've been seeing in the alerts to warnings since there isn't any action we can take to deal with them. This should reduce the number of false positive alerts in our monitoring. 
Fixes SC-9630

Change Error to Warning Logs

---

web/gds-user-ui/src/modules/dashboard/certificate/lib/contactsValidationSchema.ts

fix: remove unused object from yup validation
https://app.shortcut.com/rotational/story/9672/save-and-next-does-nothing-on-step-3-contacts

fix: remove unused object from yup validation

---

web/gds-user-ui/src/components/Form/LoginForm.tsx
web/gds-user-ui/src/components/Form/SignupForm.tsx
web/gds-user-ui/src/components/Section/CreateAccount.spec.tsx
web/gds-user-ui/src/components/Section/CreateAccount.tsx
web/gds-user-ui/src/components/Section/Login.tsx
web/gds-user-ui/src/components/ui/InputFormControl/index.tsx

sc-9879 Account Creation Page Improvements
https://app.shortcut.com/rotational/story/9879/account-creation-page-improvements

sc-9879 Account Creation Page Improvements

---

web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx

sc-9436 GDS User UI: Make stepper label clickable

---

web/gds-user-ui/src/modules/dashboard/certificate/lib/basicDetailsValidationSchema.ts

sc-9895 GDS User UI Fix Error Msg on Basic Details page

sc-9895 GDS User UI Fix Error Msg on Basic Details page

---

web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx

sc-9891 Fix Capitalization in Stepper
https://app.shortcut.com/rotational/story/9891/fix-capitalization-in-stepper

sc-9891 Fix Capitalization in Stepper

---

web/gds-admin-ui/src/components/ProfileDropdown.js

sc-10122 Change support email link to support@rotational.io
https://app.shortcut.com/rotational/story/10122/change-support-email-link-to-support-rotational-io

sc-10122 Change support email link to support@rotational.io

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNoteForm.js

sc-10113 Correct singular spelling of Business Category
https://app.shortcut.com/rotational/story/10113/correct-singular-spelling-of-business-category

sc-10113 Correct singular spelling of Business Category

---

.github/workflows/tests.yaml
web/gds-admin-ui/package.json
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/__tests__/review-note-form.spec.js
web/gds-admin-ui/src/assets/scss/app-creative.scss
web/gds-admin-ui/src/components/ResendEmail.js
web/gds-admin-ui/src/components/TextEditor/index.js
web/gds-admin-ui/src/layouts/Footer.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/ReviewForm.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/index.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/EditReviewNote.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNote.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNoteForm.js
web/gds-admin-ui/src/pages/app/details/contact/EditContactForm.js
web/gds-admin-ui/src/pages/error/PageError.js
web/gds-admin-ui/src/utils/index.js
web/gds-admin-ui/yarn.lock
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap

sc-10117 GDS Admin UI Render Reviewer Notes as safe markdown

---

web/gds-admin-ui/src/__tests__/Footer.spec.js
web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/assets/scss/custom/structure/_left-menu.scss
web/gds-admin-ui/src/layouts/Footer.js

sc-10105 Fix Admin UI Footer
https://app.shortcut.com/rotational/story/10105/fix-admin-ui-footer

sc-10105 Fix Admin UI Footer

---

web/gds-user-ui/src/components/NameIdentifiers/index.tsx

sc-10516 GDS User UI: Capitalize the word 'Identifiers'
https://app.shortcut.com/rotational/story/10516/capitalize-the-word-identifiers

sc-10516 GDS User UI: Capitalize the word 'Identifiers'

---

web/gds-admin-ui/src/__tests__/geographic.spec.js
web/gds-admin-ui/src/__tests__/review-note.spec.js
web/gds-admin-ui/src/components/Table.js
web/gds-admin-ui/src/components/TopbarSearch.js
web/gds-admin-ui/src/pages/app/lists/CertificateExpirationColumn.js
web/gds-admin-ui/src/pages/app/lists/LastUpdatedColumn.js
web/gds-admin-ui/src/pages/app/lists/NameColumn.js
web/gds-admin-ui/src/pages/app/lists/StatusColumn.js
web/gds-admin-ui/src/pages/app/lists/__tests__/CertificateExpirationColumn.spec.js
web/gds-admin-ui/src/pages/app/lists/__tests__/LastUpdatedColumn.spec.js
web/gds-admin-ui/src/pages/app/lists/__tests__/NameColumn.spec.js
web/gds-admin-ui/src/pages/app/lists/__tests__/StatusColumn.spec.js
web/gds-admin-ui/src/pages/app/lists/index.js
web/gds-admin-ui/src/utils/index.js

sc-10119 Add common name to search in List view
https://app.shortcut.com/rotational/story/10119/add-common-name-to-search-in-list-view
https://user-images.githubusercontent.com/54010836/196959329-bb36d06a-98e9-40c6-8746-88029840931d.mov

sc-10119 Add common name to search in List view

---

.github/workflows/containers.yaml
containers/build.sh
containers/docker-compose.yaml

This PR ensures that the GDS Admin UI environment variables are up to date in our build process.
This PR will be merged without review since it is part of the devops process.

Ensure admin env is set during build process

---

web/gds-admin-ui/src/sentry.js

log missed environment instead of throwing error
https://app.shortcut.com/rotational/story/10500/sentry-error-on-staging-admin-ui

fix Sentry error on staging admin UI

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/__tests__/certificate-details.js
web/gds-admin-ui/src/components/ErrorFallback.js
web/gds-admin-ui/src/components/TimeAgo.js
web/gds-admin-ui/src/components/__tests__/TimeAgo.spec.js
web/gds-admin-ui/src/pages/app/details/ReviewNotes/ReviewNote.js
web/gds-admin-ui/yarn.lock

sc-10572 "edited a few seconds ago" does not change
https://app.shortcut.com/rotational/story/10572/edited-a-few-seconds-ago-does-not-change

sc-10572 "edited a few seconds ago" does not change

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/components/BusinessInfosForm.js
web/gds-admin-ui/src/utils/index.js

sc-10560 Established On Date Format is Incorrect
https://app.shortcut.com/rotational/story/10560/established-on-date-format-is-incorrect

sc-10560 Established On Date Format is Incorrect

---

web/gds-user-ui/src/components/NeedsAttention/AttentionAlert.tsx

sc-10522 improve need attention alert component on submit type
https://app.shortcut.com/rotational/story/10522/improve-need-attention-alert-component-on-submit-type

sc-10522 improve need attention alert component on submit type

---

web/gds-admin-ui/src/pages/app/dashboard/__tests__/PendingReviewTable.spec.js
web/gds-admin-ui/src/redux/dashboard/saga.js

sc-10111 Add Pending and Recently Completed Reissuances to Dashboard view
https://app.shortcut.com/rotational/story/10111/add-pending-and-recently-completed-reissuances-to-dashboard-view

sc-10111 Add Pending and Recently Completed Reissuances to Dashboard view

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Ivms101RecordForm.js
web/gds-admin-ui/src/redux/vasp-details/sagas.js
web/gds-admin-ui/src/utils/__test__/getErrorMessage.spec.js
web/gds-admin-ui/src/utils/getError.js

sc-10563 Error when updating legal person: no error appears
https://app.shortcut.com/rotational/story/10563/error-when-updating-legal-person-no-error-appears

sc-10563 Error when updating legal person: no error appears

---

web/gds-user-ui/src/components/Navbar/Landing/MobileNav.tsx
web/gds-user-ui/src/components/Sidebar/MobileNav.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx

sc-9436 fix stepper progress alignement

sc-9436 fix stepper progress alignement

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/components/Ivms101RecordForm.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/BusinessInfo.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/Ivms101RecordForm.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/ReviewForm.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/TrisaImplementationDetailsForm.spec.js

sc-10566 Legal Entity Person Form is Posting Registration Authority
https://app.shortcut.com/rotational/story/10566/legal-entity-person-form-is-posting-registration-authority

sc-10566 Legal Entity Person Form is Posting Registration Authority

---

web/gds-user-ui/src/components/CertificateManagement/CertificateDataTable.tsx
web/gds-user-ui/src/components/CertificateManagement/MainnetCertificates.tsx
web/gds-user-ui/src/components/CertificateManagement/X509IdentityCertificateInventoryDataTable.tsx
web/gds-user-ui/src/components/CertificateRegistration/CertificateRegistrationTable.tsx
web/gds-user-ui/src/components/CollaboratorsSection/index.tsx
web/gds-user-ui/src/components/Membres/index.tsx
web/gds-user-ui/src/components/TableRow/RowItem.tsx
web/gds-user-ui/src/components/Tables/MembersRow.tsx
web/gds-user-ui/src/theme/components/Table.ts
web/gds-user-ui/src/theme/index.ts

sc-10480 refact: GDS User UI all table components style
https://app.shortcut.com/rotational/story/10480/the-table-component-needs-to-be-refactored-to-be-consistent-across-all-the-features-that-implement-data-tables

sc-10480 refact: GDS User UI  update all table components style

---

pkg/bff/models/v1/collaborator.go
pkg/bff/models/v1/collaborator_test.go

This fixes collaborator key generation so that it generates IDs with only characters that work in URLs.

Fix collaborator key generation

---

web/gds-admin-ui/src/__tests__/__snapshots__/tasks.spec.js.snap
web/gds-admin-ui/src/components/__tests__/NoData.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/dashboard/Tasks.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/dashboard/__tests__/PendingReview.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/dashboard/__tests__/getRecentVasps.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/dashboard/index.js
web/gds-admin-ui/src/redux/dashboard/saga.js
web/gds-admin-ui/src/utils/__test__/isRecent.spec.js
web/gds-admin-ui/src/utils/isRecent.js
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap

sc-10111 update title and display recent updated vasps
https://app.shortcut.com/rotational/story/10111/add-pending-and-recently-completed-reissuances-to-dashboard-view

sc-10111 update title and display recent updated vasps

---

web/gds-user-ui/src/application/routes/routes.ts
web/gds-user-ui/src/components/CertificateInventory/index.tsx
web/gds-user-ui/src/components/CertificateManagement/__tests__/MainnetTestnetCertificates.spec.tsx
web/gds-user-ui/src/components/CertificateManagement/index.tsx
web/gds-user-ui/src/components/ConfirmIdentityCertificateRequest/index.tsx
web/gds-user-ui/src/utils/menu.tsx

Sc 10614 GDS User UI :  implement identify certificate inventory list feature
https://app.shortcut.com/rotational/story/10614/gds-user-ui-implement-identify-certificate-inventory-list-feature

Sc-10614 GDS User UI :  implement identify certificate inventory list feature

---

web/gds-user-ui/src/components/Collaborators/AddCollaborator/AddCollaboratorForm.tsx
web/gds-user-ui/src/components/Collaborators/index.tsx
web/gds-user-ui/src/components/Collaborators/useFetchCollaborator.ts
web/gds-user-ui/src/hooks/useFetchUserRoles.tsx

This updates the `Add New Collaborator modal` copy and move down the place of agreement checkbox
https://app.shortcut.com/rotational/story/11379/fix-add-new-collaborator-modal-pop-up

SC-11379: Fix Add New Collaborator Modal Pop-up

---

web/gds-user-ui/src/application/routes/routes.ts
web/gds-user-ui/src/components/Account/Account.spec.tsx
web/gds-user-ui/src/components/Account/index.tsx
web/gds-user-ui/src/components/ChooseAnOrganization/index.tsx
web/gds-user-ui/src/components/Loader/TransparentLoader.tsx
web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/auth/login/auth.service.ts
web/gds-user-ui/src/modules/auth/login/user.slice.ts
web/gds-user-ui/src/modules/dashboard/organization/SwitchOrganization.tsx
web/gds-user-ui/src/utils/auth0.helper.ts
web/gds-user-ui/src/utils/constants.ts

implement the multi-organization log in feature in UI
https://app.shortcut.com/rotational/story/10906/add-orgid-to-login-endpoint

sc-7102: implement the multi organisation log in feature in UI

---

web/gds-user-ui/src/application/routes/routes.ts
web/gds-user-ui/src/components/CertificateManagement/MainnetTestnetCertificates.tsx
web/gds-user-ui/src/utils/menu.tsx

sc-11339 Refactor Certificate inventory feature
https://app.shortcut.com/rotational/story/11339/refactor-certificate-inventory-feature

sc-11339 Refactor Certificate inventory feature

---

web/gds-user-ui/src/application/routes/routes.ts
web/gds-user-ui/src/components/CertificateReview/index.tsx
web/gds-user-ui/src/components/NeedsAttention/AttentionAlert.tsx
web/gds-user-ui/src/components/ReviewSubmit/index.tsx
web/gds-user-ui/src/components/TestnetProgress/CertificateStepLabel.tsx
web/gds-user-ui/src/modules/auth/callback/index.tsx
web/gds-user-ui/src/modules/dashboard/overview/index.tsx
web/gds-user-ui/src/utils/constants.ts
web/gds-user-ui/src/utils/menu.tsx

This fixes :
- Attention Alert submit button issue 
- Certificate registration issue
.. minor improvements
https://app.shortcut.com/rotational/story/11506/fix-issues-from-edwin-feedback

Sc-11506: fix certificate route issue & minor improvement 

---

web/gds-user-ui/src/components/Collaborators/index.tsx
web/gds-user-ui/src/modules/dashboard/organization/SwitchOrganization.tsx
web/gds-user-ui/src/utils/auth0.helper.ts
web/gds-user-ui/src/utils/permission.ts

SC-11626: Fix the issue with Vasp names when switching between organizations

SC-11626: Fix the issue with Vasp names when switching between organizations

---

web/gds-user-ui/src/components/Account/index.tsx
web/gds-user-ui/src/modules/dashboard/organization/SwitchOrganization.tsx
web/gds-user-ui/src/modules/dashboard/organization/useSwitchOrganization.tsx

Still facing the spinning issue. We finally figure out the issue which comes from the response code handler. In the previous code, we just handle the 204 response code. So this PR fix definitely the issue.

sc-11626:  fix spinner issue & refactor switch org component

---

web/gds-user-ui/src/utils/auth0.helper.ts

fix: remove access token printed in console log

fix: remove access token printed in console log

---

web/gds-user-ui/src/modules/auth/login/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts

fix: org id switching issue

---

web/gds-user-ui/src/modules/auth/login/index.tsx
web/gds-user-ui/src/modules/auth/login/user.slice.ts

The switching Org from invitation link issue is coming from the misspelled params name. so this PR fixes that issue.

Fix orgid params

---

web/gds-user-ui/src/components/Collaborators/index.tsx
web/gds-user-ui/src/theme/components/Table.ts

sc-11798 Remove title casing on Contact Detail (non TSP mode)
https://app.shortcut.com/rotational/story/11798/remove-title-casing-on-contact-detail-non-tsp-mode

sc-11798 Remove title casing on Contact Detail (non TSP mode)

---

web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx
web/gds-user-ui/src/components/Sidebar/index.tsx

sc-11655 Add APP version & GIT Version in USER ADMIN UI
https://app.shortcut.com/rotational/story/11655/add-app-version-git-version-in-user-admin-ui

sc-11655 Add APP version & GIT Version in USER ADMIN UI

---

web/gds-user-ui/src/components/Sidebar/index.tsx

sc-11797 Need more whitespace between header and footer for Collaborator Information (non TSP mode)
https://app.shortcut.com/rotational/story/11797/need-more-whitespace-between-header-and-footer-for-collaborator-information-non-tsp-mode

sc-11797 Need more whitespace between header and footer for Collaborator Information (non TSP mode)

---

web/gds-user-ui/src/components/Collaborators/AddCollaborator/AddCollaboratorForm.tsx

sc-11800 Add new contact: shorten text to `Please Provide the Name and Email Address`
https://app.shortcut.com/rotational/story/11800/add-new-contact-shorten-text-to-please-provide-the-name-and-email-address

sc-11800 Add new contact: shorten text to `Please Provide the Name and Email Address`

---

web/gds-user-ui/src/application/store/stepper.slice.ts
web/gds-user-ui/src/components/CertificateReview/index.tsx
web/gds-user-ui/src/components/Collaborators/AddCollaborator/__tests__/__snapshots__/AddCollaboratorForm.spec.tsx.snap
web/gds-user-ui/src/components/Footer/Version.tsx
web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/components/Sidebar/SidebarContent.tsx
web/gds-user-ui/src/components/ui/HDivider.tsx
web/gds-user-ui/src/hooks/useFetchAppVersion.ts
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap

Sc-11944: update vasp name when registration form is submitted

Sc-11944: update vasp name when registration form is submitted

---

web/gds-admin-ui/package.json
web/gds-admin-ui/src/constants/delete-modal.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/Print.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/business-infos-form.spec.js
web/gds-admin-ui/src/pages/app/details/BasicDetails/components/__test__/trisa-implementation-details-form.spec.js
web/gds-admin-ui/src/pages/app/details/CertificateDetails/__tests__/certificate-details.spec.js
web/gds-admin-ui/src/pages/app/details/EmailLog.js
web/gds-admin-ui/src/pages/app/details/__tests__/basic-details.spec.js
web/gds-admin-ui/src/pages/app/details/__tests__/email-log.spec.js
web/gds-admin-ui/src/pages/app/details/contact/__tests__/delete-contact-prompt-modal.spec.js
web/gds-admin-ui/src/pages/app/details/index.js
web/gds-admin-ui/src/utils/test-utils.js
web/gds-admin-ui/yarn.lock

sc-9368 Display email log in admin UI
https://app.shortcut.com/rotational/story/9368/display-email-log-in-admin-ui

sc-9368 Display email log in admin UI

---

web/gds-user-ui/src/application/routes/routes.ts
web/gds-user-ui/src/components/Account/Account.spec.tsx
web/gds-user-ui/src/components/Account/index.tsx
web/gds-user-ui/src/components/AddNewVaspForm/AddNewVaspForm.tsx
web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/CertificateDetails/CertificateDetails.tsx
web/gds-user-ui/src/components/CertificateReview/TrixoReviewDataTable.tsx
web/gds-user-ui/src/components/ChooseAnOrganization/ChooseAnAccount.stories.tsx
web/gds-user-ui/src/components/ChooseAnOrganization/index.tsx
web/gds-user-ui/src/components/Collaborators/EditCollaborator/__tests__/__snapshots__/EditCollaboratorModal.spec.tsx.snap
web/gds-user-ui/src/components/ContactForm/index.tsx
web/gds-user-ui/src/components/CountryOfRegistration/index.tsx
web/gds-user-ui/src/components/NameIdentification/index.tsx
web/gds-user-ui/src/components/NetworkAnnouncements/caroussels.tsx
web/gds-user-ui/src/components/Sidebar/MobileNav.tsx
web/gds-user-ui/src/components/TableRow/index.tsx
web/gds-user-ui/src/components/TrisaImplementation/index.tsx
web/gds-user-ui/src/components/TrisaImplementationForm/index.tsx
web/gds-user-ui/src/components/ui/DeleteButton.stories.tsx
web/gds-user-ui/src/components/ui/DeleteButton.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/defaultValues.ts
web/gds-user-ui/src/modules/dashboard/certificate/registration.tsx

sc-11879 Allow Navigating with Tab between input fields
https://app.shortcut.com/rotational/story/11879/allow-navigating-with-tab-between-input-fields

sc-11879 Allow Navigating with Tab between input fields

---

web/gds-admin-ui/src/pages/app/details/BasicDetails/dashboard/VaspsByCountryChart.js

https://app.shortcut.com/rotational/story/10110/add-bar-chart-representing-counts-of-vasps-by-country
I have added the No Data component to avoid the chart to be displayed without data

sc-10110 add No Data component

---

web/gds-user-ui/src/utils/menu.tsx

display certificate management menu

---

cmd/bffutil/main.go

This adds a command to `bffutil` to sort organizations on the user's appdata record in Auth0. We recently changed the way organizations are added and removed from user Auth0 records in sc-11172 so that the list is always sorted. However, we need to fix this retroactively for existing users in order for the implemented sorting logic to work.
This command can be run outside of the pod since it only needs to interact with Auth0 and it sorts every user's current org list and pushes the appdata with the sorted list to Auth0.
SC-12601
This command correctly makes the Auth0 updates and is idempotent (it can be run multiple times and produces the same result).

bffutil: Appdata sort orgs command

---

pkg/gds/admin.go

Fixes SC-12213 - a small bug where the VASP country code was missing. 
This should be a quick and simple review!

VASP Country Code Fix

---

web/gds-user-ui/src/components/ChooseAnOrganization/usePaginate.tsx
web/gds-user-ui/src/components/Icon/index.tsx
web/gds-user-ui/src/components/Section/CreateAccount.tsx
web/gds-user-ui/src/components/Section/Login.tsx
web/gds-user-ui/src/components/StepsButtons/index.tsx
web/gds-user-ui/src/hooks/useCertificateStepper.tsx
web/gds-user-ui/src/modules/auth/login/index.tsx
web/gds-user-ui/src/modules/auth/register/index.tsx

This adds github & microsoft authentication
https://www.awesomescreenshot.com/video/16126161?key=a7c19712e884884ea48ebdcfa74000d7

add social MSFT & Github auth

---

web/gds-admin-ui/package.json
web/gds-admin-ui/yarn.lock

Fixes SC-15878
https://app.shortcut.com/rotational/story/15878/update-gds-admin-ui-yarn-lock

sc-15878 update gds admin ui yarn lock

---

pkg/bff/models/v1/errors.go
pkg/bff/models/v1/registration.go
pkg/bff/models/v1/registration_test.go

This adds an an initial implementation for basic details validation for the BFF registration form.

Basic details validation

---

pkg/bff/models/v1/registration.go
pkg/bff/models/v1/registration_test.go
web/gds-user-ui/src/components/Contacts/index.tsx

A few more fixes and updates for legal person validation step.

Final Updates from Legal Person Validation

---

pkg/bff/models/v1/errors.go
pkg/bff/models/v1/registration.go
pkg/bff/models/v1/registration_test.go
pkg/gds/gds.go
pkg/gds/gds_test.go
pkg/utils/patterns.go

This implements the TRISA details step of the registration form validation.

Validate TRISA details step 5

---

pkg/bff/api/v1/api.go
pkg/bff/gds.go
pkg/bff/models/v1/registration.go
pkg/bff/models/v1/registration_test.go
pkg/bff/models/v1/testdata/registration_form.json

Modifies JSON marshaling and unmarshaling so that only the fields in the current step are serialized. 
Fixes SC-17360

Custom marshaling for registration form

---

pkg/bff/models/v1/errors.go
pkg/bff/models/v1/registration.go
pkg/bff/models/v1/registration_test.go

This implements the validation method for the TRIXO questionnaire in the registration form.

Validate TRIXO form step 4

---

pkg/bff/gds_test.go
pkg/bff/models/v1/registration_test.go
pkg/bff/testdata/bad_registration_form.pb.json

This adds test coverage for load and save registration when partial forms are provided.

Load and save partial tests

---

containers/docker-compose.yaml
web/gds-user-ui/src/components/CertificateReview/LegalPersonReviewDataTable.tsx

Displays legal name in the `Review` form. Fixes SC-17597.
https://www.awesomescreenshot.com/video/17780337?key=b324b18910c3cdac3ac3bbfd603d76c6

Sc 17597/legal person

---

.husky/pre-commit
web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/Modal/ConfirmationResetFormModal.tsx
web/gds-user-ui/src/hooks/useCertificateStepper.tsx

This adds a default value to the state at the first basic detail component rerender.

set default stepper value

---

pkg/bff/models/v1/registration.go
pkg/bff/models/v1/registration_test.go

This fixes the following validation issues:
1. Ignore C9 constraint error when validating legal person
2. Contact phone number is not required for technical
3. Do not return an error for missing license number other jurisdictions

Register form validation fixes

---

web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx
web/gds-user-ui/src/constants/trixo.ts

This fixes, the select option value of the regulator program input.
Update Partial  to Partially

fix:  misspelled regulatory program option name

---

web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx
web/gds-user-ui/src/constants/trixo.ts
web/gds-user-ui/src/hooks/useCertificateStepper.tsx
web/gds-user-ui/src/modules/dashboard/certificate/lib/basicDetailsValidationSchema.ts
web/gds-user-ui/src/modules/dashboard/certificate/lib/trixoQuestionnaireValidationSchema.ts

Remove partially option from required regulatory program
https://www.awesomescreenshot.com/video/18051465?key=e8e28dbef657dfa593885ba49fa3ac43

Remove partially option from required regulatory program

---

web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx

`isDirty` method from react hook form doesn't trigger when an option is selected which doesn't help to know if thoses fields change. So this fixes the issue of not saving some data.

Fix Trixo questionnaire select option value  

---

web/gds-user-ui/src/modules/dashboard/certificate/lib/basicDetailsValidationSchema.ts

Remove unused packages

---

pkg/bff/api/v1/api.go
pkg/bff/api/v1/client.go
pkg/bff/api/v1/client_test.go
pkg/bff/api/v1/errors.go
pkg/bff/errors.go
pkg/bff/members.go
pkg/bff/members_test.go
pkg/bff/server.go
pkg/bff/verification.go
pkg/bff/verification_test.go

Adds middleware that adds context about whether or not the organization is verified in the mainnet or the testnet. 

Verification Status Middleware

---

web/gds-user-ui/src/modules/dashboard/member/Components/DirectoryNotification.tsx
web/gds-user-ui/src/modules/dashboard/member/index.tsx

Adds permanent notification message to the Member Directory page.
Fixes SC-18422

Adds notification message to member page

---

web/gds-user-ui/src/modules/dashboard/member/components/MemberHeader.tsx
web/gds-user-ui/src/modules/dashboard/member/hooks/useExportMembers.tsx
web/gds-user-ui/src/modules/dashboard/member/utils.ts
web/gds-user-ui/src/utils/utils.ts

This adds the export button logic, the user should be able to export member list data
https://www.awesomescreenshot.com/video/18949559?key=c32bf35fdeb88a825e5ff43bb138ac4c

implement export button logic

---

web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/modules/dashboard/member/components/MemberNetworkSelect.tsx
web/gds-user-ui/src/modules/dashboard/member/components/__tests__/MemberNetworkSelect.spec.tsx
web/gds-user-ui/src/modules/dashboard/member/components/__tests__/__snapshots__/MemberNetworkSelect.spec.tsx.snap
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap

Implements logic for `MemberSelectNetwork` component to get value selected by the user.

Sc 18427/network logic

---

web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/modules/dashboard/member/__mocks__/index.ts
web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/__tests__/__snapshots__/MemberModal.spec.tsx.snap
web/gds-user-ui/src/modules/dashboard/member/components/MemberTableRow.tsx
web/gds-user-ui/src/modules/dashboard/member/components/__tests__/__snapshots__/MemberTableRows.spec.tsx.snap
web/gds-user-ui/src/modules/dashboard/member/utils.ts
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap

Corrects bug to display the correct `Status` in the member list table.
Fixes SC-18719

Sc 18719/status

---

web/gds-user-ui/src/components/Section/__tests__/__snapshots__/Membership.spec.tsx.snap
web/gds-user-ui/src/hooks/useToast.tsx
web/gds-user-ui/src/modules/dashboard/member/components/MemberHeader.tsx
web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/MemberModal.tsx
web/gds-user-ui/src/modules/dashboard/member/hooks/useExportMembers.tsx
web/gds-user-ui/src/modules/dashboard/member/hooks/useFetchMember.tsx
web/gds-user-ui/src/modules/verify/__snapshots__/verify.spec.tsx.snap

With this fixes, user should be able to fetch member detail endpoints

Fix useFetchMember hooks

---

pkg/store/leveldb/leveldb_test.go
pkg/store/trtl/trtl_test.go

This adds some missing test cases for the list organizations store method.

List organizations tests

---

web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/MemberModal.tsx

This fix should allow the user to open the detail modal

Fix modal issue from toast implementation

---

web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/MemberModal.tsx

Fixes issue where the member's name wasn't appearing in the member detail modal.
Fixes SC-18797

Displays name in modal

---

web/gds-user-ui/src/constants/basic-details.ts
web/gds-user-ui/src/modules/dashboard/member/hooks/useFetchMember.tsx
web/gds-user-ui/src/modules/dashboard/member/utils.ts

This fix should allow the user to fetch member detail  for each distinct member
https://www.awesomescreenshot.com/video/19100514?key=e49bb173671939ebb9f766dff63d94b5

Fix useFetchMember issue

---

web/gds-user-ui/src/modules/dashboard/certificate/lib/trisaImplementationValidationSchema.ts
web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/MemberModal.tsx

Amends regex in Trisa form validation to fix page load error and adds max height to member detail modal.
Fixes SC-18800 & SC-18806
https://www.awesomescreenshot.com/video/19103749?key=2a6115150c098e0bf97b00725e8e8f76

Updates trisa regex and adds max height

---

pkg/bff/gds.go
pkg/bff/gds_test.go

This adds a quick fix for the missing business category when the BFF sends the register request to GDS and additional testing to verify the fix.
When submitting a registration via the BFF/GDS user UI, the business category should now be respected, rather than being set to `UNKNOWN_ENTITY`.

Fix missing business category

---

web/gds-user-ui/src/components/CertificateReview/ReviewsSummary.tsx
web/gds-user-ui/src/hooks/useCertificateStepper.tsx

This adds a minor update to refresh the review page which allow user to have the updated errors 
https://www.awesomescreenshot.com/video/19108127?key=8419b4e6cfa036bfcf6355674d3b8e76

Sc-18664: refresh the review page

---

web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/Copy.tsx
web/gds-user-ui/src/modules/dashboard/member/components/MemberModal/MemberModalContent.tsx
web/gds-user-ui/src/modules/dashboard/member/memberType.ts
web/gds-user-ui/src/modules/dashboard/member/utils.ts

Displays the `Business Category` as a text value and not a number.
Fixes SC-18847

Adds temp switch for business category values

---

pkg/bff/auth/auth.go
pkg/bff/gds.go
pkg/bff/members.go
pkg/bff/organization.go
pkg/bff/users.go
pkg/gds/admin.go
pkg/gds/admin/v2/auth.go
pkg/gds/certman/certs.go
pkg/gds/gds.go
pkg/gds/members.go
pkg/trtl/trtl.go

Reduces Sentry usage by changing some sentry calls to log messages instead and eliminating `sentry.Debug` calls.
This PR will be merged without review for devops purposes.

Reduce Sentry Usage

---

.github/workflows/cleanup.yaml

This adds a workflow that runs daily or on a manual trigger that cleans up the old images in GCR.

Add gcr cleanup workflow

---

pkg/bff/api/v1/api.go
pkg/bff/api/v1/client.go
pkg/bff/api/v1/client_test.go
pkg/bff/gds.go
pkg/bff/gds_test.go

Refactors the lookup autocomplete to return a map of name to common names rather than a list of strings.

Refactor Lookup Autocomplete

---

pkg/bff/config/config.go
pkg/bff/config/config_test.go
pkg/gds/config/config.go
pkg/gds/config/config_test.go
pkg/utils/ensign/config.go
pkg/utils/ensign/config_test.go
pkg/utils/ensign/errors.go

This adds initial Ensign configuration to support the upcoming network activity publisher in the GDS and subscriber in the BFF.

Ensign configuration

---

web/gds-user-ui/src/components/Section/SearchDirectory.tsx
web/gds-user-ui/src/constants/basic-details.ts
web/gds-user-ui/src/modules/home/useFetchLookup.ts

This PR solves these problems:
- Shows lookup results.
- Displays `NON VASP ENTITY` under VASP Category.
- Improves autocomplete to only show user query data.

Sc-20385: GDS fixes after QA

---

containers/docker-compose.yaml
pkg/bff/config/config.go
pkg/bff/config/config_test.go
pkg/bff/server.go
pkg/gds/config/config.go
pkg/gds/config/config_test.go
pkg/gds/service.go
pkg/utils/activity/config.go
pkg/utils/activity/config_test.go
pkg/utils/activity/errors.go
pkg/utils/activity/event.go
pkg/utils/activity/publisher.go
pkg/utils/activity/publisher_test.go
pkg/utils/ensign/config.go

This adds a handler singleton for publishing activities, moves some configuration around to integrate with GDS and the BFF, and adds an API for "adding" activity from external go routines.

Activity publisher handler

---

web/gds-user-ui/src/components/Collaborators/index.tsx
web/gds-user-ui/src/components/Collaborators/useFetchCollaborator.ts
web/gds-user-ui/src/modules/dashboard/collaborator/getCollaboratorType.ts

Enhance the error handling for the collaborator feature.

sc-20409: Enhance the error handling for the collaborator feature

---

web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/Contacts/index.tsx
web/gds-user-ui/src/components/LegalPerson/LegalForm.tsx
web/gds-user-ui/src/components/LegalPerson/index.tsx
web/gds-user-ui/src/components/RegistrationForm/CertificateSteps.tsx
web/gds-user-ui/src/components/TrisaImplementation/index.tsx
web/gds-user-ui/src/components/TrixoQuestionnaire/index.tsx
web/gds-user-ui/src/hooks/useFetchCertificateStep.tsx

This PR aims to enhance the issue of data not updating within the stepper and also seeks to refine the reset form functionality.

Refactor Stepper 

---

cmd/gdsutil/build.sh
cmd/gdsutil/main.go
pkg/gds/admin.go
pkg/gds/emails/client.go
proto/gds/models/v1/models.proto

On SendVerifyContact the verification token is now required otherwise the method returns an error.

Require Email Verification Token

---

pkg/bff/server.go
pkg/utils/activity/publisher.go

Starts the activity subscriber in the BFF for Ensign/TRISA integration.
Is this all that is needed to start the activity monitor?

Start Activity Subscriber in BFF

---

pkg/gds/admin.go
pkg/gds/admin_test.go
pkg/gds/emails/client.go
pkg/gds/emails/client_test.go
pkg/gds/gds.go
pkg/gds/gds_test.go

This PR implements a quick hotfix to ensure Bitbromo receives email verification tokens.

Fix Admin Resend

---

pkg/gds/certman/certs.go

This updates the error returns for certificate reissuance so that instead of a custom error the actual error is returned to make it easier to track down issues.

Pass certificate reissuance errors to sentry

---

web/gds-user-ui/src/components/BasicDetail/index.tsx
web/gds-user-ui/src/components/BasicDetailsForm/index.tsx
web/gds-user-ui/src/components/Contacts/index.tsx
web/gds-user-ui/src/components/TrisaImplementation/TrisaImplementationForm.tsx
web/gds-user-ui/src/components/TrisaImplementation/index.tsx
web/gds-user-ui/src/components/TrixoQuestionnaireForm/index.tsx

Adjusts `Basic Details` form and `TRISA` form width to `100%` to be more consistent with other form sections.
https://www.awesomescreenshot.com/video/23901062?key=c7e2415efda4b24ea373348d8cb09557

Sets full width for basic detail and trisa forms

---

web/gds-user-ui/src/modules/home/index.tsx

Hides the `NetworkActivity` component.
https://www.awesomescreenshot.com/image/45501756?key=057a059822876e2f6c299554d5820d35

Hides network activity monitor

---

cmd/gdsutil/main.go

Adds a contacts export command to the `gdsutil` helper.
This PR will be merged without review.

Contacts Export

---

web/gds-user-ui/src/components/ReviewSubmit/index.tsx

- Aligns buttons on the `Review Submission` page so that they should be at the same level.
- Uses `grid` to improve the responsiveness of each card.
- Adjusts padding to prevent appearance of excessively large buttons on smaller screens. 
- Groups `button` styles to improve organization.
https://www.awesomescreenshot.com/video/24267122?key=19dfbe4cbeb67d79107e644b5ea36e03

Align buttons on review submission page

---

web/gds-user-ui/src/components/CertificateReview/BasicDetailsReviewDataTable.tsx
web/gds-user-ui/src/components/CertificateReview/LegalPersonReviewDataTable.tsx
web/gds-user-ui/src/components/CertificateReview/TrisaImplementationReviewDataTable.tsx

Update font sizes on review page to be more consistent.
https://www.awesomescreenshot.com/video/24607469?key=e79e27c765cbcd104ea08f084035c03e

Improve review page font size consistency

---

.github/workflows/tests.yaml
containers/gds-user-ui/Dockerfile

Update node version for user UI

---

web/gds-user-ui/src/modules/dashboard/certificate/lib/trixoQuestionnaireValidationSchema.ts

Converts currency in the `TRIXO` form to a string and verifies the type to fix a TypeError.

Fix .replace not a function TypeError

---

.github/workflows/cleanup.yaml
.github/workflows/containers.yaml
.github/workflows/staging.yaml
.github/workflows/tests.yaml
containers/bff/Dockerfile
containers/cathy/Dockerfile
containers/gds/Dockerfile
containers/trtl/Dockerfile
containers/trtlsim/Dockerfile

Enables multi-architecture builds for docker images.
This PR will be merged without review.

Multi Architecture Containers

---

cmd/gdsutil/certs.go
cmd/gdsutil/main.go
cmd/gdsutil/vasp.go

Adds a `gdsutil` command to cancel a certificate request.
This PR will be merged without review.

Cancel Certificate Requests

---

cmd/gdsutil/directory.go
cmd/gdsutil/main.go

Adds a gdsutil script to update the registered directory in the VASP database.
This PR will be merged without review.

Migrate Registered Directory

---

cmd/gdsutil/main.go
cmd/gdsutil/vasp.go
pkg/models/v1/vasp.go

Update the VASP fields that are easily updatable using JSON from the CLI.
Will be merged without review.

Update VASP from JSON using CLI
